- tests/nightwatch/modules/thresholds/user-test-scenarios.json
scenarios A31-A32 from spreadsheet
> Extra threshold scenarios

- cla_public/static-src/stylesheets/_shame.scss
- cla_public/static-src/stylesheets/main.scss
- cla_public/templates/_sidebar.html
- cla_public/templates/cookies.html
- cla_public/templates/index.html
- cla_public/templates/privacy.html
> Cookies page

- tests/nightwatch/modules/thresholds/user-test-scenarios.json
> pensioner disregard savings limits

- tests/nightwatch/modules/constants.js
- tests/nightwatch/specs/savings-page.js
savings page no longer lets you enter less than 500 for valuables
> fix savings page test

- cla_public/static-src/javascripts/modules/currency-formatting.js
- cla_public/static-src/stylesheets/forms/_fieldset.scss
- cla_public/static-src/stylesheets/ie/ie6.scss
- tests/nightwatch/specs/currency-formatting.js
* fix currency formatting bug in all IE versions
* fix blue legends in IE7
> IE currency bug fix + CSS fix

- cla_public/static-src/stylesheets/forms/_form-option-list.scss
- cla_public/templates/macros/form.html
[PT](https://www.pivotaltracker.com/story/show/88592876)
> Add separator for last item on benefits page

- cla_public/apps/contact/forms.py
- cla_public/templates/contact.html
[PT](https://www.pivotaltracker.com/story/show/89272442)
> Copy changes

- cla_public/templates/help-organisations.html
- cla_public/templates/macros/element.html
- cla_public/templates/result/confirmation.html
- cla_public/templates/result/face-to-face.html
[Pivotal story](https://www.pivotaltracker.com/n/projects/1159820/stories/89608636)
> satisfaction survey prompt

- cla_public/templates/income.html
> copy change

- Makefile
- package.json
- tests/nightwatch/browserstack-integration.conf.js
- tests/nightwatch/browserstack-integration.json
- tests/nightwatch/modules/common-functions.js
- tests/nightwatch/specs/current/404-page.js
- tests/nightwatch/specs/current/about-page.js
- tests/nightwatch/specs/current/benefits-page.js
- tests/nightwatch/specs/current/categories-of-law.js
- tests/nightwatch/specs/current/clear-session.js
- tests/nightwatch/specs/current/confirmation-page.js
- tests/nightwatch/specs/current/currency-formatting.js
- tests/nightwatch/specs/current/eligible-page.js
- tests/nightwatch/specs/current/face-to-face-page.js
- tests/nightwatch/specs/current/income-page.js
- tests/nightwatch/specs/current/ineligible-outcomes.js
- tests/nightwatch/specs/current/other-benefits-page.js
- tests/nightwatch/specs/current/outgoings-page.js
- tests/nightwatch/specs/current/property-page.js
- tests/nightwatch/specs/current/savings-page.js
- tests/nightwatch/specs/current/sidebar.js
- tests/nightwatch/specs/legacy/thresholds.js
* run tests on browserstack
* fix a few tests to work in IE8 (no :last-child)
* increase time allowed when waiting for elements
* tweak validation testing to not resubmit form to check for every single error
> run tests on browserstack

- cla_public/apps/checker/constants.py
A new disregarded benefit should be added to the site from April 13th.
[Pivotal story](https://www.pivotaltracker.com/story/show/91280458)
> add new disregarded benefit to constants

- cla_public/apps/checker/tests/test_money_interval.py
- cla_public/apps/checker/validators.py
- tests/nightwatch/specs/current/income-page.js
- tests/nightwatch/specs/current/other-benefits-page.js
- tests/nightwatch/specs/current/outgoings-page.js
- tests/nightwatch/specs/current/property-page.js
value there and the field is required
this is because a user putting in a blank value but choosing a interval period
is currently getting two errors
> Make the MoneyIntervalRequiredValidator stop further validation if there is no

- cla_public/apps/contact/forms.py
[PT](https://www.pivotaltracker.com/story/show/92435868)
> Include help text with example for phone number

- cla_public/templates/checker/result/confirmation.html
[Pivotal](https://www.pivotaltracker.com/story/show/94508636)
> update copy for confirmation page in DV cases

- cla_public/templates/checker/result/face-to-face.html
[Pivotal](https://www.pivotaltracker.com/story/show/94508888)
> copy for mental health f2f page

- cla_public/templates/scope/ineligible.html
[PT for education](https://www.pivotaltracker.com/story/show/95235350)
[PT for employment](https://www.pivotaltracker.com/story/show/95237530)
> ineligible copy for employment and education

- cla_public/templates/_phase-tag.html
[Pivotal](https://www.pivotaltracker.com/story/show/95257242)
> remove link to Welsh in scope diagnosis

- cla_public/apps/checker/api.py
- cla_public/apps/contact/forms.py
- cla_public/apps/scope/api.py
- requirements/base.txt
for getting Welsh text choices from the GraphML
> support for sending current locale to backend API

- cla_public/static-src/javascripts/modules/address-finder.js
- cla_public/static-src/stylesheets/forms/_field-error.scss
- cla_public/templates/contact.html
- tests/nightwatch/specs/current/eligible-page.js
[Pivotal](https://www.pivotaltracker.com/story/show/93978358)
> show postcode message as help, not error

- cla_public/apps/base/constants.py
- cla_public/apps/base/forms.py
- cla_public/apps/base/views.py
- cla_public/config/common.py
- cla_public/libs/views.py
- cla_public/templates/checker/benefits.html
- cla_public/templates/emails/zendesk-feedback.txt
- cla_public/templates/emails/zendesk-reasons-for-contacting.txt
- cla_public/templates/feedback.html
- cla_public/templates/macros/element.html
- cla_public/templates/macros/form.html
- cla_public/templates/reasons-for-contacting.html
- cla_public/templates/scope/diagnosis.html
- tests/nightwatch/specs/current/contact-page.js
Interstitial form to determine why users are dropping out of the process submitting to Zendesk
> why are users dropping out / reasons for contacting

- cla_public/templates/scope/ineligible.html
legal aid may still be available in exceptional cases, see link
> ineligible copy tweaks

- cla_public/apps/contact/fields.py
- cla_public/apps/contact/tests/test_mail.py
because no more operator callback slots would be available
> email tests failed when run too late in the day

- cla_public/apps/contact/views.py
- cla_public/libs/views.py
- cla_public/templates/index.html
but it's linked from the home page where no session existed
> contact page was not reachable without session

- cla_public/static-src/javascripts/modules/find-legal-adviser.js
- cla_public/static-src/javascripts/modules/form-errors.js
[PT](https://www.pivotaltracker.com/story/show/97727828)
> Fix XHR form submission for Legal Adviser page

- cla_public/static-src/stylesheets/_flash-messages.scss
- cla_public/templates/base.html
This stops it being affected by sidebar column
> Place flash message outside of .main-content

- cla_public/static-src/stylesheets/_answers-summary.scss
- cla_public/static-src/stylesheets/_progress.scss
- cla_public/templates/checker/_progress.html
- cla_public/templates/scope/diagnosis.html
- split scope diagnosis progress from means test progress
- update progress styles
> Updates to progress indicator

- cla_public/apps/checker/tests/smoketests.py
- cla_public/apps/checker/tests/test_integration.py
- tests/nightwatch/commands/scopeDiagnosis.js
- tests/nightwatch/modules/constants.js
- tests/nightwatch/specs/about-page.js
- tests/nightwatch/specs/benefits-page.js
- tests/nightwatch/specs/child-benefits.js
- tests/nightwatch/specs/clear-session.js
- tests/nightwatch/specs/confirmation-page.js
- tests/nightwatch/specs/currency-formatting.js
- tests/nightwatch/specs/eligible-page.js
- tests/nightwatch/specs/face-to-face-page.js
- tests/nightwatch/specs/income-page.js
- tests/nightwatch/specs/other-benefits-page.js
- tests/nightwatch/specs/outgoings-page.js
- tests/nightwatch/specs/progress-indicator.js
- tests/nightwatch/specs/property-page.js
- tests/nightwatch/specs/review-page.js
- tests/nightwatch/specs/savings-page.js
- tests/nightwatch/specs/scope-diagnosis.js
depends on [cla_backend/375](https://github.com/ministryofjustice/cla_backend/pull/375)
> test fixes for scope tree changes

- cla_public/templates/index.html
- cla_public/templates/scope/diagnosis.html
depends on [cla_backend#378](https://github.com/ministryofjustice/cla_backend/pull/378)
> showing security message about keeping data safe

- cla_public/templates/contact.html
[PT#99686328](https://www.pivotaltracker.com/story/show/99686328)
> Add link to call charges on DA contact page

- cla_public/apps/checker/session.py
> stronger session encryption

- cla_public/apps/base/views.py
- cla_public/apps/checker/session.py
- cla_public/apps/checker/views.py
- cla_public/apps/scope/views.py
- cla_public/templates/_ga-outcome-pageview.html
- cla_public/templates/checker/result/confirmation.html
- cla_public/templates/checker/result/eligible-f2f.html
- cla_public/templates/checker/result/eligible.html
- cla_public/templates/checker/result/face-to-face.html
- cla_public/templates/checker/result/ineligible.html
- cla_public/templates/reasons-for-contacting.html
- cla_public/templates/scope/ineligible.html
- cla_public/templates/scope/mediation.html
This adds 8 virtual page views for outcomes:
- /vpv/outcome/referred/help-organisations/scope
- /vpv/outcome/referred/help-organisations/means
- /vpv/outcome/referred/f2f/scope
- /vpv/outcome/referred/f2f/means
- /vpv/outcome/referred/mediation/scope
- /vpv/outcome/eligible
- /vpv/outcome/provisional
- /vpv/outcome/incomplete
> GA: Virtual page views for outcomes

- cla_public/apps/base/views.py
- cla_public/templates/base.html
- cla_public/templates/online-safety.html
- cla_public/templates/scope/diagnosis.html
> Add 'Stay safe online' page

- cla_public/apps/checker/constants.py
- cla_public/apps/checker/tests/test_integration.py
- cla_public/templates/checker/result/face-to-face.html
- cla_public/templates/contact.html
- cla_public/templates/errors/4xx.html
- cla_public/templates/errors/5xx.html
- cla_public/templates/index.html
- cla_public/templates/scope/diagnosis.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
- cla_public/translations/messages.pot
[PR#561](https://github.com/ministryofjustice/cla_public/pull/561) needs to be merged in first!
depends on [backend PR#388](https://github.com/ministryofjustice/cla_backend/pull/388)
> copy & translation updates

- cla_public/apps/checker/fields.py
- cla_public/apps/checker/forms.py
- cla_public/static-templates/errors/50x.html
- cla_public/templates/_phase-tag.html
- cla_public/templates/base.html
- cla_public/templates/checker/review.html
- cla_public/templates/contact.html
- cla_public/templates/index.html
- cla_public/templates/macros/element.html
- cla_public/templates/scope/diagnosis.html
- cla_public/templates/session-expired.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
- cla_public/translations/messages.pot
- tests/nightwatch/commands/scopeDiagnosis.js
depends on [cla_public#390](https://github.com/ministryofjustice/cla_backend/pull/390)
> accessibility copy changes

- cla_public/static-src/javascripts/modules/form-errors.js
- cla_public/static-src/javascripts/modules/skip-to-content.js
- cla_public/static-src/stylesheets/_alerts.scss
- cla_public/static-src/stylesheets/_answers-summary.scss
- cla_public/static-src/stylesheets/_confirmation.scss
- cla_public/static-src/stylesheets/_forms.scss
- cla_public/static-src/stylesheets/_layout.scss
- cla_public/static-src/stylesheets/_phase-banner.scss
- cla_public/static-src/stylesheets/_progress.scss
- cla_public/static-src/stylesheets/forms/_error-summary.scss
- cla_public/static-src/stylesheets/forms/_field-error.scss
- cla_public/static-src/stylesheets/forms/_fieldset.scss
- cla_public/static-src/stylesheets/forms/_form-group.scss
- cla_public/static-src/stylesheets/ie/_ie-common.scss
- cla_public/static-src/stylesheets/ie/ie7.scss
- cla_public/static-src/stylesheets/ie/ie8.scss
- cla_public/templates/base.html
- cla_public/templates/checker/review.html
- cla_public/templates/macros/form.html
- cla_public/templates/macros/review.html
- cla_public/templates/scope/diagnosis.html
- package.json
- tests/nightwatch/commands/conditionalFormSubmit.js
- tests/nightwatch/commands/ensureFormValidation.js
- tests/nightwatch/commands/interstitialPage.js
- tests/nightwatch/commands/scopeDiagnosis.js
- tests/nightwatch/specs/about-page.js
[PT#100105622](https://www.pivotaltracker.com/story/show/100105622)
> Form error summaries

- cla_public/static-src/javascripts/modules/find-legal-adviser.js
- cla_public/static-src/stylesheets/_find-legal-adviser.scss
- cla_public/static-src/stylesheets/_utilities.scss
- cla_public/templates/_resources.html
- cla_public/templates/checker/result/_find-legal-adviser.html
- cla_public/templates/checker/result/confirmation.html
- cla_public/templates/checker/result/eligible.html
- cla_public/templates/checker/result/ineligible.html
- cla_public/templates/checker/review.html
- cla_public/templates/contact.html
- cla_public/templates/cookies.html
- cla_public/templates/errors/5xx.html
- cla_public/templates/feedback-confirmation.html
- cla_public/templates/index.html
- cla_public/templates/interstitial.html
- cla_public/templates/macros/element.html
- cla_public/templates/macros/help-orgs.html
- cla_public/templates/online-safety.html
- cla_public/templates/privacy.html
- cla_public/templates/scope/diagnosis.html
- cla_public/templates/scope/ineligible.html
- cla_public/templates/scope/mediation.html
- cla_public/templates/session-expired.html
[PT#100105536](https://www.pivotaltracker.com/story/show/100105536)
> Improvements in accessibility

- cla_public/apps/contact/views.py
- cla_public/libs/views.py
as GDS has now removed link from start page
> once again prevent direct access to contact page

- cla_public/templates/scope/ineligible.html
- tests/nightwatch/specs/scope-diagnosis.js
depends on [cla_backend#405](https://github.com/ministryofjustice/cla_backend/pull/405)
> immigration scope

- cla_public/static-src/stylesheets/_phase-banner.scss
- cla_public/static-templates/errors/50x.html
- cla_public/templates/_phase-tag.html
service has passed live assessment
> remove BETA tag

- cla_public/apps/checker/views.py
- cla_public/static-src/javascripts/modules/find-legal-adviser.js
- cla_public/templates/checker/result/_find-legal-adviser.html
[PT#103795608](https://www.pivotaltracker.com/story/show/103795608)
> Add GA pageviews and event for Find Legal Adviser in-page interactions

- cla_public/templates/checker/result/eligible.html
[PT##103773722](https://www.pivotaltracker.com/story/show/103773722)
> FE: Update copy on contact CLA for eligible page

- cla_public/apps/checker/constants.py
- cla_public/apps/checker/views.py
- cla_public/apps/scope/api.py
- cla_public/static-src/javascripts/modules/truncate-list.js
- cla_public/templates/macros/help-orgs.html
- cla_public/templates/scope/ineligible.html
[PT#100402136](https://www.pivotaltracker.com/story/show/100402136)
> Niche categories of law

- cla_public/static-src/javascripts/modules/form-errors.js
- cla_public/static-src/javascripts/modules/properties.js
- cla_public/static-src/javascripts/modules/truncate-list.js
- cla_public/templates/checker/property.html
- cla_public/templates/macros/help-orgs.html
[PT#103903970](https://www.pivotaltracker.com/story/show/103903970)
> Additional GA events

- README.mdown
added virtualenv steps to readme
> amended readme to add virtualenv steps

- README.mdown
> removed some unwanted quotes

- cla_public/apps/checker/cait_intervention.py
Was always returning false and consequently incorrectly served develop branch of remote config file for prod environment
> Fix environment check

- .github/CODEOWNERS
- README.md
Documents the release process for this application for both non-production and production releases.
🔎 Nicer link to the new section: https://github.com/ministryofjustice/cla_public/blob/release-process/README.md#releasing
👨‍💻 Added a `CODEOWNERS` file to mark the repository owned by the @ministryofjustice/laa-get-access team.
> LGA-122: Release process

- .github/PULL_REQUEST_TEMPLATE.md
Adds this pull request template 😄
> Add pull request template to the project

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- cla_public/apps/base/healthchecks.py
- cla_public/apps/base/tests/test_healthchecks.py
- cla_public/apps/base/views.py
- requirements/base.txt
Releases:
- #733: Update deployment instructions for Docker builds
- #735: Add pull request template to the project
- #736: Allow branches with slashes to build Docker images
- #734: LGA-112: Add disk size to healthchecks
> Release, 22th August 2018

- README.md
We switched the default branch on this repository to `master`.
This pull request updates the deployment instructions to reflect that.
> Update deployment process for "master" default branch

- .circleci/config.yml
- cla_public/config/docker.py
- kubernetes_deploy/staging/deployment.yml
- kubernetes_deploy/staging/ingress.yml
- kubernetes_deploy/staging/service.yml
This pull request configures Kubernetes to host the application's docker image.
The ECR repository has been changed to the one that is used by Kubernetes.
> Configure kubernetes deployment files

- .circleci/config.yml
- Dockerfile
- README.md
Optimises the `Dockerfile` by
- Installing node.js via https://deb.nodesource.com/setup_8.x.
- Copying minimal files required to install dependencies to avoid unnecessary reinstalling of python or npm packages any time a file changes.
- Renaming `ADD` to `COPY` as it is discouraged to use `ADD` for copying files.
- Moving EXPOSE and CMD to the end of the file as that is where they are conventionally located.
- Grouping commands related to `nginx` together.
- Grouping commands related to `uwsgi` together.
- Ordering packages alphabetically on separate lines as it makes it more readable and easier to find what is installed.
- Adding `LABEL` instructions as per http://docs.projectatomic.io/container-best-practices/#_recommended_labels_for_your_project.
**`--label` arguments have been added …
> Optimise Dockerfile

- .pre-commit-config.yaml
- cla_public/apps/checker/cait_intervention.py
- cla_public/apps/checker/constants.py
- cla_public/apps/checker/means_test.py
- cla_public/apps/checker/session.py
- cla_public/apps/contact/views.py
- docs/development.md
- docs/installation.md
- requirements/dev.txt
- setup.py
Ignore settings for flake8 until they're inverted in LGA-419, currently wallowing in the backlog and unlikely to make it into the next sprint.
Mark acknowledged/ticketed violations
> LGA-418 Pre-commit hooks

- cla_public/apps/base/views.py
- cla_public/apps/checker/means_test.py
- cla_public/apps/checker/session.py
- cla_public/apps/checker/tests/test_means_test.py
- cla_public/apps/checker/tests/test_payloads.py
- cla_public/apps/checker/tests/utils/forms_utils.py
- cla_public/apps/checker/utils.py
- cla_public/apps/contact/tests/test_availability.py
- cla_public/apps/contact/views.py
- cla_public/libs/utils.py
- Minor fixes to areas with excessive CC
- Replace assigned lambda expressions
> LGA-450 Flake8 fixes

- docs/monitoring.md
These changes document accessing dashboards and logs in Kubernetes.
None.
> LGA-481: Document accessing dashboards and logs in Kubernetes

- .tx/config
- README.md
- docs/translation.md
- requirements/dev.txt
- requirements/jenkins.txt
Document tested steps to translate `cla_public` using existing packages and tools.
Source and translations successfully pushed to and pulled from https://www.transifex.com/ministry-of-justice/cla-public/
> LGA-491 & LGA-494 Document tested translation procedure

- README.md
Applies #806 by hand.
This is a workaround to get CI passing.
None.
We will need to work on a collaborative setup for our CI steps.
> Apply shuckc/patch 1

- cla_public/apps/contact/fields.py
- cla_public/apps/contact/tests/test_availability.py
- cla_public/libs/call_centre_availability.py
> **NOTE: Do not merge until removal of callback capping has been confirmed with Agilisys.**
- Remove Monday morning call-back capping
- Retain and invert tests to ensure callback capping is removed
- Fix previous test so `tuesday` is actually a Tuesday(!)
> LGA-447 Remove Monday morning callback capping

- kubernetes_deploy/production/dashboard.yml
- kubernetes_deploy/staging/dashboard.yml
Update Grafana dashboards to work with the latest cloud platform changes
> LGA-511 - Update Grafana dashboards to work with the latest cloud platform changes

- Dockerfile
- docs/translation.md
- manage.py
Fix, re-instate, and document previous translation management commands
> Update documented translation steps

- cla_public/apps/checker/constants.py
- cla_public/apps/checker/views.py
- cla_public/libs/laalaa.py
Convert LAALAA_PROVIDER_CATEGORIES_MAP values to lists
Query LAALAA with each category
Concatenate results
> LGA-444 Lookup providers from multiple categories

- cla_public/libs/laalaa.py
Add count to merged_data for results template.
> LGA-444 Add count to merged_data

- cla_public/config/common.py
- cla_public/templates/base.html
- kubernetes_deploy/development/deployment.yml
- kubernetes_deploy/production/deployment.yml
Move the GDS GA_D to an environment variable.
Also renamed the GA_ID environment variable to MOJ_GA_ID as the application now has
multiple GA ids
Required.
> GDS Google Analytics environment variable

- cla_public/templates/privacy.html
Updates the privacy policy to reflect:
-- dual operation during October by HGS and Agilisys
-- information on cookie tracking and collection of data by GDS
Amended so the cookies URL is now a relative path, not a full URL.
> LGA 653 HGS privacy update

- cla_public/apps/base/views.py
Pass _ga parameter from /start to the /scope/diagnosis page redirect
> Pass _ga parameter from /start to the /scope/diagnosis page

- cla_public/apps/base/__init__.py
Persist query parameters during locale redirect
> Persist query parameters during locale redirect

- cla_public/templates/privacy.html
Changes to privacy HTML to delete references to Agilisys and reflect HGS sole operation.
Deletes references to Agilisys.
LGA-654
https://dsdmoj.atlassian.net/browse/LGA-654
> LGA-654 Update privacy for HGS sole operation

- cla_public/templates/interstitial.html
Fixes bug in production. Will need revisiting for desired behaviour, but small cost
Required.
> Remove singular version of alt help

- cla_public/templates/interstitial.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
LGA 883 Updates styles on the legal aid is available page
> Means landing page

- cla_public/apps/checker/views.py
- cla_public/libs/tests/test_laalaa.py
- cla_public/static-src/stylesheets/main.scss
- cla_public/templates/checker/result/_find-legal-adviser.html
- cla_public/templates/checker/result/eligible-f2f.html
- cla_public/templates/checker/result/face-to-face.html
- cla_public/templates/laalaa.html
- cla_public/templates/macros/form.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
Updates most elements on the legal-adviser page.
> LGA-882 End page with postcode check

- cla_public/apps/checker/forms.py
- cla_public/static-src/javascripts/modules/form-errors.js
- cla_public/static-src/stylesheets/main.scss
- cla_public/templates/checker/additional-benefits.html
- cla_public/templates/checker/benefits.html
- cla_public/templates/macros/form.html
LGA-884
Updates the page to use the new GDS styles for tickboxes.
> Your Benefits page - updated styles

- cla_public/apps/contact/constants.py
- cla_public/static-src/stylesheets/forms/_form-subfield.scss
- cla_public/static-src/stylesheets/main.scss
- cla_public/templates/_valuables-info.html
- cla_public/templates/checker/about.html
- cla_public/templates/checker/additional-benefits.html
- cla_public/templates/checker/property.html
- cla_public/templates/checker/savings.html
- cla_public/templates/contact.html
- cla_public/templates/macros/form.html
- cla_public/templates/macros/subform.html
Changed radio buttons to new GDS format
Changed contact us time to popup depending on answer
Changed list of valuable items to an accessible DL list in a details tag
Updated classes and structure of popup fields
Added custom label functionality
> LGA-822 radio buttons

- cla_public/apps/contact/forms.py
- cla_public/static-src/stylesheets/_confirmation.scss
- cla_public/static-src/stylesheets/main.scss
- cla_public/templates/checker/result/confirmation.html
- cla_public/templates/macros/form.html
Changes confirmation screen to new standard.  
> LGA-828 Confirmation Panel Page

- cla_public/static-src/javascripts/modules/form-errors.js
- cla_public/templates/base.html
- cla_public/templates/contact.html
- cla_public/templates/macros/element.html
- cla_public/templates/macros/form.html
Converted error messages to new style.
This appears to also fix 922
> LGA-894 Error Messages

- cla_public/static-src/stylesheets/main.scss
- cla_public/templates/base.html
- cla_public/templates/checker/property.html
- cla_public/templates/contact.html
- cla_public/templates/macros/form.html
- cla_public/templates/macros/subform.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
Changes all secondary buttons to the GDS style as per the design system.
> LGA-833 secondary button styling

- cla_public/static-src/javascripts/modules/properties.js
Progressive enhancement for when a new property is added, the focus moves to the new property.
> LGA-834 Add Property Button

- cla_public/templates/_modal-dialog.html
- cla_public/templates/checker/result/confirmation.html
- cla_public/templates/macros/element.html
- cla_public/templates/scope/ineligible.html
- cla_public/templates/scope/mediation.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
Removes incorrectly used aria attributes to make link accessible.  
Made appropriate changes in Welsh translation file.  
Corrected unrelated links in Welsh translation file.
> LGA-842 link accessibility

- cla_public/static-src/javascripts/modules/address-finder.js
- cla_public/templates/checker/result/_find-legal-adviser.html
- cla_public/templates/contact.html
- cla_public/templates/macros/subform.html
Styles postcode as per GDS Design System.  
Forces uppercase text.
Adds in the warning based on Scottish etc postcode that exists on the other postcode page.
> LGA-831 Postcode Lookup Styling and Accessibility

- cla_public/translations/cy/LC_MESSAGES/messages.po
Adds in GDS classes to a couple of Welsh links that were missed in the main ticket
> LGA-924 missing bit - welsh link styling

- cla_public/config/local.py.example
- docs/installation.md
- Update installation README to include npm install and the gulp build
- Update local.py.example to include proper import and remove non-working DebugToolbarExtension extension
> Update Installation README

- cla_public/static-src/javascripts/modules/conditional-subfields.js
- cla_public/static-src/javascripts/modules/form-errors.js
- cla_public/static-src/stylesheets/main.scss
- cla_public/templates/checker/additional-benefits.html
- cla_public/templates/checker/benefits.html
- cla_public/templates/checker/income.html
- cla_public/templates/checker/outgoings.html
- cla_public/templates/checker/property.html
- cla_public/templates/macros/form.html
Introduces a new pattern for asking for income per period, where the user can select "per week", "per year" etc.  
> LGA-845 currency per period

- cla_public/templates/_back-navigation.html
- cla_public/templates/base.html
- cla_public/templates/scope/diagnosis.html
Removed merits answer log and added back buttons to means and merits.
> LGA-824 navigation

- cla_public/apps/checker/forms.py
- cla_public/templates/checker/result/eligible-f2f.html
- cla_public/templates/checker/result/ineligible.html
- cla_public/templates/privacy.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
- cla_public/translations/messages.pot
New phrases added
Some phrases were deleted as part of the automatic update process, these have been restored.
> LGA-954 Welsh Part 2

- cla_public/templates/macros/subform.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
Fixes a few omissions from the previous PR for this ticket
> LGA-954 missed off bit

- cla_public/static-src/stylesheets/_scope-diagnosis.scss
- cla_public/templates/scope/diagnosis.html
Changed style for scope selection boxes
> LGA-986 Scope Selection Arrows

- cla_public/static-src/javascripts/modules/cookie-settings.js
- cla_public/static-src/stylesheets/main.scss
- cla_public/templates/_cookie-consent-form.html
- cla_public/templates/_cookie-popup.html
- cla_public/templates/cookies.html
- cla_public/templates/moj_template_base.jinja
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
Changes the cookie banner to a more responsive design.
> LGA-807 Cookie banner

- cla_public/templates/errors/5xx.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
Updated the textphone number to the new number on the 5xx.html page and in the translation files.
Old number: 80010
New number: 78900
> LGA-1078 updated textphone number

- cla_public/templates/base.html
> LGA-1099 Google Analytics code correction

- cla_public/apps/base/extensions.py
- cla_public/apps/base/tests/test_extensions.py
- cla_public/static-src/stylesheets/main.scss
- cla_public/templates/base.html
Moved the python code to extensions.py
> LGA-1095 Code improvement

- cla_public/templates/base.html
- On activating the quick exit button (fleeing), the session is ended.
- On fleeing, a detailed précis is sent to GA.
- The GA code has been put on one line with a variable to reduce repetition.
> LGA-1099 Google Analytics and Session Expiry JS

- bin/staging_deploy.sh
- helm_deploy/cla-public/templates/ingress.yaml
Enables the Ingress resource when doing the staging deploy of master branch
Fixes the API version, which I had mistakenly set to v1
Will need the existing Ingress manually removed before deploying, as they would conflict
> LGA-1159 - Staging ingress

- cla_public/config/common.py
- cla_public/templates/base.html
- helm_deploy/cla-public/values-production.yaml
> LGA-1234 - Adding google tag manager

- cla_public/config/common.py
- cla_public/static-src/javascripts/modules/cookie-banner.js
- cla_public/templates/base.html
- helm_deploy/cla-public/values-production.yaml
- helm_deploy/cla-public/values-staging.yaml
> LGA-1246 - Add GTM code staging

- cla_public/apps/base/extensions.py
Adds n62 to the list of pages where the Quick Exit button is shown.
> LGA-1249 DA route without Quick Exit button given button

- cla_public/config/common.py
- cla_public/templates/base.html
- helm_deploy/cla-public/values-production.yaml
- helm_deploy/cla-public/values-staging.yaml
GTM uses this to identify environments for testing and deploying changes, so we need to make sure our environments are labelled correctly.
> 1 = Live
2 = Latest
3 = Staging
> LGA-1268 - Set gtm_preview value

- cla_public/templates/scope/diagnosis.html
- cla_public/templates/session-expired.html
Added title attribute to scope options and start again button
> LGA-1265 Added Title Text to Scope links and start again button.

- cla_public/templates/_cookie-consent-form.html
- cla_public/templates/checker/result/_find-legal-adviser.html
- cla_public/templates/errors/5xx.html
- cla_public/templates/privacy.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
Added the new Welsh translations to the translation file
Added trans tags around some untranslated text
Changed some normal quotes to smart quotes
> LGA-1218 New welsh translations implemented

- cla_public/translations/cy/LC_MESSAGES/messages.po
Added the two missing phrases with their translations
> LGA-1295 Missing QE translations

- cla_public/static-src/stylesheets/main.scss
Changed the CSS to mimic the new GDS currency pattern.
> LGA-1279 New Currency Pattern

- cla_public/templates/base.html
Changed quick exit button wording.
Removed subtext.
> LGA-1284 Quick Exit wording

- cla_public/templates/base.html
> LGA-1314 Added GA code to no-options error condition.

- cla_public/templates/base.html
- cla_public/templates/scope/diagnosis.html
Changes the approach to test for the title rather than duplicate the title logic.  
> LGA-1314 no option tracking (take 2)

- cla_public/apps/checker/fields.py
- cla_public/apps/checker/forms.py
- cla_public/apps/checker/tests/test_money_field.py
- cla_public/apps/checker/tests/test_money_interval.py
- cla_public/apps/checker/tests/test_validation.py
- cla_public/apps/checker/validators.py
- cla_public/apps/contact/forms.py
- cla_public/templates/checker/result/confirmation.html
- cla_public/templates/errors/5xx.html
- cla_public/templates/moj_template_base.jinja
- cla_public/translations/cy/LC_MESSAGES/messages.po
Applies the new error structure (with different messages for frequency and amount etc) to more fields.
Updates the error text.
Applies Welsh changes to error text.
Applies some Welsh changes unrelated to error text.
Minor amendments to content.
Updates Welsh footer, including link to Welsh licence.
> LGA-940 errors and welsh changes

- cla_public/templates/checker/result/_find-legal-adviser.html
> LGA-1321 removed duplicate ID

- cla_public/static-src/javascripts/modules/find-legal-adviser.js
- cla_public/static-src/stylesheets/_find-legal-adviser.scss
Moved the aria-expanded code so it only fires when expanded rather than on every click.
CSS changes for narrowish screens.
> LGA-1326 Aria Expanded attribute

- cla_public/static-src/javascripts/modules/truncate-list.js
- cla_public/templates/base.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
Added `aria-label` with more descriptive text
> LGA-1341 Added ARIA label with more descriptive text

- cla_public/templates/checker/result/_find-legal-adviser.html
> LGA-1339 fix typo

- helm_deploy/cla-public/values-production.yaml
Put CLA into maintenance mode
Site will be offline during the migration of cla_backend to the cloud platform environment
> LGA-1389 - Put CLA into maintenance mode

- helm_deploy/cla-public/values-production.yaml
Reverts ministryofjustice/cla_public#997
> Revert "LGA-1389 - Put CLA into maintenance mode"

- cla_public/static-src/javascripts/modules/form-errors.js
- cla_public/static-src/stylesheets/main.scss
- package-lock.json
- package.json
NPM installed the latest govuk-frontend using `npm install govuk-frontend --save`
Amendments to SCSS and JS for our own custom currency controls to better tie in with new styles.
> LGA-1358 GDS Design System update

- cla_public/static-src/javascripts/modules/find-legal-adviser.js
- cla_public/templates/checker/result/_find-legal-adviser.html
New data attribute with the information for the GTM analytics.  
Changed JS to retain the data attribute when amending the HTML.
> LGA-1413 Put GTA stuff in data attribute

- cla_public/static-src/stylesheets/_sidebar.scss
CSS fix to eliminate dual colour/wrong colour bar on family route
> LGA-1398 Added CSS to fix bug

- helm_deploy/cla-public/values-dev.yaml
- helm_deploy/cla-public/values-staging.yaml
> LGA-1436 - Update backend staging domain

- cla_public/config/common.py
- cla_public/templates/base.html
- helm_deploy/cla-public/values-dev.yaml
- helm_deploy/cla-public/values-production.yaml
- helm_deploy/cla-public/values-staging.yaml
Remove MOJ GA ID from code as this done through GTM now
> LGA-1236 - Remove MOJ GA ID from code as this done through GTM now

- cla_public/static-src/stylesheets/_find-legal-adviser.scss
Adds focus styling to the map - missed off in the previous PR for LGA-1511
> LGA-1511 LARP map focus

- cla_public/templates/macros/subform.html
Defines a class attribute for all drop-downs.  
> LGA-1538 erratic drop-down fields on contact page

- requirements/base.txt
Amends the version for cla_common
> LGA-1567-christmas-hours

- cla_public/apps/base/extensions.py
- cla_public/apps/base/utils.py
- cla_public/apps/checker/constants.py
- cla_public/apps/checker/views.py
- cla_public/apps/scope/views.py
- New category for Modern Slavery and Human Trafficking
- New function for analysing the codes of previous pages in new `utils.py` file
- Adapted from the existing QE check
> LGA-1570 LARP Modern Slavery category

- cla_public/libs/call_centre_availability.py
- cla_public/libs/tests/test_utils.py
- cla_public/translations/cy/LC_MESSAGES/messages.po
- Translate AM/PM time suffix to welsh
- Translate day names to welsh
- Translate date ordinals(i.e st,nd,th) to welsh
> LGA-990 - Translate contact dropdown

- cla_public/templates/privacy.html
Updates the privacy policy with the latest text supplied by the LAA legal team.
Welsh translations have been sent separately and the Welsh page will be updated when the translated text is returned in 2 weeks.
LGA-1600
https://dsdmoj.atlassian.net/browse/LGA-1600
> Feature-LGA-1600-updated-privacy

- docs/translation.md
> New manual translation process

- cla_public/apps/checker/constants.py
Adding route for larp modern slavery
> LGA-1570 Adding route for larp modern slavery

- helm_deploy/cla-public/values-staging.yaml
> LGA-1638 - Use static uat backend

- cla_public/apps/checker/views.py
- cla_public/templates/checker/review.html
This fixes the defect that stop someone changing data that would have made them ineligible.  
> For example a person mistakenly enters 100,000 for their wage which then skips to the review page.  However when on the review page it didn't display the data that was entered, and then they wouldn't know to go back and correct it.
I reintroduced the use review_steps method which had never been removed from the code.
> LGA 1636 - Display full summary

- cla_public/config/common.py
- cla_public/static-src/javascripts/modules/smart-sruvey.js
- cla_public/templates/base.html
- helm_deploy/cla-public/values-production.yaml
- helm_deploy/cla-public/values-staging.yaml
Adding smart survey integration
> LGA-1680 - Adding smart survey integration

- cla_public/translations/cy/LC_MESSAGES/messages.po
Adds Welsh translations for updates in English to the accessibility statement.
Related ticket
https://dsdmoj.atlassian.net/browse/LGA-1623
> LGA-1623 - Welsh accessibility statement

- cla_public/templates/privacy.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
Adds missing Welsh translations for the Privacy Policy.
Related ticket
https://dsdmoj.atlassian.net/browse/LGA-1624
> LGA-1624 - Welsh privacy policy translations

- cla_public/static-src/javascripts/modules/textarea-character-count.js
- cla_public/translations/cy/LC_MESSAGES/messages.po
Adds or updates the Welsh translations for the Contact Form on the Contact CLA page.
No.
JIRA ticket
https://dsdmoj.atlassian.net/browse/LGA-1620
> LGA-1620-Welsh-character-counts-contact-form

- cla_public/apps/base/views.py
Restart session if its not already available when giving feedback
> LGA-989 - Restart session if its not already available when giving feedback

- cla_public/templates/scope/mediation.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
Adds Welsh translations for the mediation redirect page.
https://dsdmoj.atlassian.net/browse/LGA-1687
> LGA-1687-mediation-welsh

- package.json
- Updated govuk-frontend package 
None
> Update GDS styles package to version 3.13.0

- .github/workflows/semgrep.yml
Adds a github action to run a semgrep scan on the repo when a pull request is created
> LGA-1968 - Add semgrep github action

- .circleci/config.yml
- requirements/base.txt
Deploy production to the live cluster
> LGA-1926 - Deploy production to the live cluster

- .circleci/config.yml
Remove staging_deploy_live1 and update references to laa-cla-public-live-1 to refer to context laa-cla-public
> LGA 1958 CLA Public Staging Live-1 Clean-up

- .circleci/config.yml
removed production_deploy_live1 deployment
> LGA 1959 removed production_deploy_live1 deployment

- helm_deploy/cla-public/templates/ingress.yaml
> LGA 2049 Implement WAF in monitor mode.

- helm_deploy/cla-public/templates/ingress.yaml
- helm_deploy/cla-public/values.yaml
Updates code that adds maintenance mode page so it can be switched without a code update.
> WIP LGA-2083 Add maintenance mode page without code update

- helm_deploy/cla-public/templates/ingress.yaml
Removes 1.21 version of ingress.
New version in place and weighting already set to zero for old version of ingress
> LGA-2125 Update ingress to version 1.22 - second PR

- cla_public/apps/contact/views.py
- cla_public/config/common.py
- cla_public/django_to_jinja.py
- cla_public/templates/base.html
- cla_public/templates/contact.html
- cla_public/templates/macros/emergency_message.html
- helm_deploy/cla-public/values.yaml
Changed emergency message to take new variables for title and text
Required.
> LGA 2299 Maintenance Message in banner

- helm_deploy/cla-public/templates/ingress.yaml
> LGA-2306: ModSecurity enabled in blocking mode with full ruleset.

- .circleci/config.yml
> LGA-1966 - Add end-2-end tests to CircleCI

- docker/nginx.conf
-[x] Updated nginx config to resolve IOErrors from uwsgi on client abort.
> LGA-2264: Updated nginx config to resolve IOErrors

- .circleci/config.yml
> Pipeline e2e OIDC update

- cla_public/templates/online-safety.html
Updating the Internet Explorer link to the "Stay safe online" guideline.
> LGA-2700: 💬 Update Internet Explorer link

- cla_public/apps/base/govuk_notify/api.py
- Fixes the typos in the send_email docstring
> LGA 2788 Fix Typos in send_email docstring

- docs/installation.md
Adds depth to the installation docs, so I can set the backend and other options.
> Install docs improved to include setting the backend

- cla_public/templates/interstitial.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
- cla_public/translations/messages.pot
Updating old url http://www.interpretingline.co.uk/vbooking.html to https://www.interpretingline.co.uk/EBooking 
[LGA-2911](https://dsdmoj.atlassian.net/browse/LGA-2911)
[LGA-2911]: https://dsdmoj.atlassian.net/browse/LGA-2911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LGA-2911 updating all URLS for interpreting line to new url for booking

- cla_public/apps/checker/views.py
- cla_public/apps/scope/views.py
- cla_public/templates/interstitial.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
- cla_public/translations/messages.pot
Change wording around HLPAS categories financial qualification
> LGA2920 - Change wording around HLPAS categories financial qualification

- cla_public/apps/base/views.py
- cla_public/templates/index.html
Add start page for bsl users and redirect them to the /contact page
> LGA-3154 - Add start page for bsl users and redirect them to the /contact page

- cla_public/templates/interstitial.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
BSL legal aid available content changes.
> BSL legal aid available content changes

- cla_public/static-src/javascripts/modules/gtm-data.js
- cla_public/templates/checker/result/find-legal-adviser-search/result.html
Add GA tracking with partial postcode, category and closest search result for Mini Fala search
I was thinking of adding number of results but seems to always be 100 regardless of distance.
> LGA-2997 WIP Add FALA search event

- cla_public/static-src/javascripts/modules/conditional-subfields.js
Reset the contact phone number when another contact method is selected.
> LGA-3200 - Reset the contact phone number when another contact method is selected

- bin/production_deploy.sh
- bin/staging_deploy.sh
- bin/staging_multideploy.sh
- helm_deploy/cla-public/templates/_helpers.tpl
- helm_deploy/cla-public/values.yaml
https://dsdmoj.atlassian.net/jira/software/c/projects/LGA/issues/LGA-3235
Pull IP addresses for repository as a proof of concept. Feedback welcome. Sorry no Jira ticket on commit as this was something that was born in LAA eng leadership, but if we are happy with this approach for pulling IPs, which will vary depending on app, we can use this ticket to track the work and pull into sprint.
The IP address list is updated and should include all IPs that you expect.
https://raw.githubusercontent.com/ministryofjustice/laa-ip-allowlist/main/cidrs.txt
CLA Public only applies this to staging, so it's a good place to try this.
> LGA-3235 Pull shared laa ips

- bin/staging_multideploy.sh
- helm_deploy/cla-public/values-staging.yaml
- Updates CLA Public static staging to use CLA Backend
- UAT branches still point to CLA Backend UAT
> Update public staging to use backend staging

- cla_public/templates/privacy.html
- cla_public/translations/cy/LC_MESSAGES/messages.po
- cla_public/translations/en/LC_MESSAGES/messages.po
- cla_public/translations/messages.pot
- Updates the privacy policy for links to the new survey, hosted on a third party site.
New content is found here: [https://dsdmoj.atlassian.net/jira/software/c/projects/LGA/boards/226?selectedIssue=LGA-3575](https://dsdmoj.atlassian.net/jira/software/c/projects/LGA/boards/226?selectedIssue=LGA-3575)
> LGA 3575: Update privacy policy for new survey

- helm_deploy/cla-public/values-dev.yaml
- helm_deploy/cla-public/values-production.yaml
- helm_deploy/cla-public/values-staging.yaml
- helm_deploy/cla-public/values.yaml
Setup routing cookie for legacy service.
> Setup routing cookie for legacy service
