ministryofjustice/cla_public

cla_public/apps/checker/api.py, cla_public/apps/checker/decorators.py, cla_public/apps/checker/tests/test_api_timeout.py, cla_public/templates/benefits.html, cla_public/templates/macros/form.html, cla_public/templates/problem.html
Rather than throwing a 500 error
=> Display a form validation error if the backend API times out

cla_public/static-src/javascripts/modules/user-testing.js
* Double-click BETA tag to enable testing mode on problem page
* Select one of the categories in the scope of the scope checker (debt, discrimination, education, family, housing, violence, immigration)
* The prototype scope checker (on AWS S3) will be opened in front of the application for testing
* The application will continue to the means test in the original tab
* When the scope checker ends at a positive result, the user clicks 'Continue' in the prototype and that window closes, revealing the means test
* When the scope checker ends at a negative result, that is displayed in the prototype. The tester can then close that window and return the original application to the start manually
Will only apply on localhost or on demo environment.
=> temporary JS to route to scope checker prototype for user testing

Makefile
For individual tests use:
`make test spec=spec-file-name` (without extension)
=> Add spec paths to Makefile

cla_public/static-src/javascripts/modules/conditional-subfields.js, cla_public/templates/macros/form.html
Add wildcard support to trigger element visibility through `data-controlled-by` when any value is `data-control-value` is selected.
=> Improvements for conditional fields

cla_public/apps/contact/tests/test_notes.py, cla_public/static-src/javascripts/modules/textarea-character-count.js, cla_public/static-src/stylesheets/_forms.scss, cla_public/static-src/stylesheets/forms/character-counter.scss, cla_public/templates/contact.html, tests/nightwatch/specs/current/contact-page.js
Usage:
Add `data-character-count='4000'` as attribute on textarea.
The value has to be a number. A small template for counter is also required (see contact.html)
[#92355174]
=> Implement textarea character counter

cla_public/apps/checker/tests/test_integration.py, cla_public/apps/scope/tests/test_diagnosis_api.py
so that graph node rearrangement does not affect tests nor URLs (important for google analytics)
depends on [cla_backend#361](https://github.com/ministryofjustice/cla_backend/pull/361)
[Fixes #95035940]
=> scope graphs use "permanent" IDs

cla_public/templates/checker/_progress.html
sometimes when navigating around, perhaps after session expires, users could land on a page that was unavailable in their flow. this is a quick fix to prevent the progress bar causing a 500. a full fix would redirect users to a different page (e.g. start or review)
=> progress bar fix

babel.cfg, cla_public/templates/checker/result/_find-legal-adviser.html, cla_public/templates/checker/result/confirmation.html, cla_public/templates/contact.html, cla_public/templates/emails/confirmation.txt, cla_public/templates/errors/5xx.html, cla_public/templates/help-organisations.html, cla_public/templates/macros/review.html, cla_public/templates/scope/diagnosis.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po, cla_public/translations/messages.pot
untranslated strings marked for translation and some sentences combined into single messages
(because sentence fragments cannot always be translated when split up)
=> missing translations

cla_public/apps/base/constants.py, cla_public/apps/base/forms.py, cla_public/apps/base/tests/test_reasons_for_contacting.py, cla_public/apps/base/views.py, cla_public/apps/checker/api.py, cla_public/apps/contact/views.py, cla_public/libs/views.py, cla_public/templates/contact.html, cla_public/templates/emails/zendesk-reasons-for-contacting.txt, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po, cla_public/translations/messages.pot, requirements/base.txt, tests/nightwatch/specs/reasons-for-contacting.js
when a user drops out of the scope/means test flow, they are presented with a form to find out why they want to get in touch. the form was previously sent to zendesk
[Fixes #96775836]
depends on [cla_backend#363](https://github.com/ministryofjustice/cla_backend/pull/363) and [cla_common#31](https://github.com/ministryofjustice/cla_common/pull/31)
=> reasons for contacting are now stored in DB

package.json, tasks/serve.js
HTML Injector attempts to watch template files edits and reload
only corresponding part of edited HTML instead of the whole page.
=> Add Browser Sync HTML Injector

cla_public/templates/index.html
no longer mentioning family mediation as it was throwing users off
=> start page copy – what does legal aid cover?

scripts/jenkins/build.py
NB: if two jobs are running on the same jenkins slave then one may break the other
=> jenkins job fix: nightwatch fails to clean up these process

cla_public/static-src/javascripts/modules/properties.js
When property is injected via XHR it loses form field bindings (such as conditional fields, label select etc)
Reinitialise all moj modules when the page is updated.
=> Fix multiple properties JS bug

cla_public/apps/checker/api.py, cla_public/apps/checker/tests/test_api_already_saved_error.py, cla_public/apps/checker/tests/test_validation.py, cla_public/apps/contact/forms.py, cla_public/apps/contact/validators.py, cla_public/apps/contact/views.py, cla_public/templates/macros/review.html, requirements/base.txt
- if backend returns case already exists error then retrieve the case ref form the backend and redirect to confirmation without re-saving case
=> Fix Sentry errors

cla_public/apps/base/views.py, requirements/base.txt, requirements/production.txt
Add missing dependencies and upgrade pyopenssl
Django version needs to be pinned < 2.0.0 to avoid a major version
upgrade. Additionally, pyopenssl needs to be upgraded to avoid an error
on no attribute 'SSL_ST_INIT'
=> Add app version standard env support

cla_public/apps/checker/tests/test_cait_intervention.py, cla_public/apps/scope/tests/test_diagnosis_api.py, docker/cla_public.ini
Several tests failed when run on their own. In some cases they could be
fixed with a basic mock, in another I moved it to an integration
test module.
=> Fix tests failing due to lack of backend

.circleci/config.yml
- Adds CircleCI job for Python unit tests.
- Adds CircleCI job for building the `cla_public` Docker image.
As a follow-up, we should remove both of these functions from our self-hosted Jenkins instance.
The Docker images are assumed to be stored in Amazon Elastic Container Registry. This might change in the future to Docker Hub or quay.io.
=> Move unit tests and Docker build to CircleCI

.circleci/config.yml, tests/nightwatch/ci.json, tests/nightwatch/specs/about-page.js, tests/nightwatch/specs/benefits-page.js, tests/nightwatch/specs/child-benefits.js, tests/nightwatch/specs/clear-session.js, tests/nightwatch/specs/confirmation-page.js, tests/nightwatch/specs/contact-page.js, tests/nightwatch/specs/currency-formatting.js, tests/nightwatch/specs/eligible-page.js, tests/nightwatch/specs/face-to-face-page.js, tests/nightwatch/specs/income-page.js, tests/nightwatch/specs/other-benefits-page.js, tests/nightwatch/specs/outgoings-page.js, tests/nightwatch/specs/progress-indicator.js, tests/nightwatch/specs/property-page.js, tests/nightwatch/specs/reasons-for-contacting.js, tests/nightwatch/specs/review-page.js, tests/nightwatch/specs/savings-page.js, tests/nightwatch/specs/scope-diagnosis.js
Adds `browser-test` job to CircleCI that (attempts) to run browser tests via Nightwatch.js and headless Chrome.
🚨 **Disabled most of the tests**
Most of the tests failed at the step `Scope diagnosis` with
```
✖   - URL is /scope/diagnosis  - expected "/scope/diagnosis" but got: "http://localhost:5000/session-expired"
```
All of these tests have been disabled, leaving only 2 running. The plan is to fix forward.
**Version bumps**
I had to update the hardcoded versions of `selenium-server` and `chromedriver` to reflect the newer versions installed at the moment via `selenium-standalone`.
**Build image change**
The new job uses `circleci/python:2.7-node-browsers` as the builder image. To make the Python dependency cache reusable, I had to change the `test` job's image to …
=> [LGA-57] Build browser tests as a separate CI job

.circleci/config.yml
Switches the Amazon Elastic Container Registry added in #705 back to the original Docker registry.
We need to do this as our deployment process does not currently handle other Docker registries and this is the path to least resistance on making everything build from CircleCI until we can switch the deployment infrastructure to Kubernetes.
I had to lock the remote Docker version to 17.03-ce due to the Docker registry's compatibility issues with newer versions.
=> LGA-103: Switch to previous docker registry

README.md, cla_public/apps/base/filters.py, cla_public/apps/base/tests/test_filters.py, cla_public/config/testing.py
The Legal Adviser Location Search API this application currently uses to query postcodes has a pagination component in the response.
The API's expected response on the first page is:
```
{
"count": 3768,
"next": "https://staging.laalaa.dsd.io/legal-advisers/?page=2&postcode=BS20BL",
"previous": null,
"results": [<snip>
```
The API's expected response on the second page is:
```
{
"count": 3768,
"next": "https://staging.laalaa.dsd.io/legal-advisers/?page=3&postcode=BS20BL",
"previous": "https://staging.laalaa.dsd.io/legal-advisers/?page=1&postcode=BS20BL",
"results": [<snip>
```
If we upgrade the API application's dependencies then the `previous` link will change by losing the `page=1` query parameter:
```diff
-"previous": "https://staging.laalaa.dsd.io/legal-advisers/?page=1&postcode=BS20BL …
```
=> LGA-153: Allow application to use pagination URLs that are missing page numbers

README.md
Updates deployment instructions in the Readme.
The Docker builds now happen on CircleCI, so starting a Docker build on Jenkins is no longer necessary.
=> Update deployment instructions for Docker builds

.circleci/config.yml
Replaces `/` characters with `-` characters in Docker tag names.
Currently, builds on branches that have slashes (`/`) in them will always fail the Docker build as we try to incorporate the branch names into the tags.
However, Docker specifies in https://docs.docker.com/engine/reference/commandline/tag/#usage:
> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.
Out of these constraints, this changeset only replaces slashes with dashes.
Our current example of such branch names come from dependabot, which typically creates names like `dependabot/pip/raven-6.9.0`.
Related to …
=> Allow branches with slashes to build Docker images

cla_public/apps/base/healthchecks.py, cla_public/apps/base/tests/test_healthchecks.py, cla_public/apps/base/views.py, requirements/base.txt
Extends the healthcheck endpoint with a disk size check.
It reports on the available and total disk space in megabytes and percent. It will **fail** the check when the available disk space gets at or under 2.0%.
💚 Test coverage has been added for `/healthcheck.json` and the two checks.
The response code of `/healthcheck.json` now changes to `503 Service Unavailable` if any of the checks return falsey (`False` or `None`).
`requests` and `urllib3` have been upgraded to their latest versions. I wanted to update `requests` only but `urllib3` is required both by that and our application so they had to be upgraded together.
=> LGA-112: Add disk size to healthchecks

requirements/base.txt
Bumps `markdown2` dependency.
~~This fixes [CVE-2018-5773](https://nvd.nist.gov/vuln/detail/CVE-2018-5773).~~
=> Bump markdown2 dependency

.circleci/config.yml, .dockerignore, Dockerfile
Fixes scheduling same day calls during summer time (more details in the example below).
Our `cla_public` containers need to run on `Europe/London` timezone due to the code involved around scheduling calls is timezone agnostic.
Rewriting the code involved to be timezone-aware is a massive undertaking due to arching into other shared dependencies.
Given these considerations and our nature of deployment being in UK only, the prudent thing seems to be to ensure the timezone of our deployments to be set to London.
10:43 in London time is 9:43 in UTC (the current setting), which means callbacks for the same day would be available from 12:00 (9:43 + 2 hours), instead of the expected 13:00.
✨ A test has been added to the Docker build on CI to validate that the resulting images are correctly …
=> LGA-87: Schedule same day calls after 2+ hours during summer time

.circleci/config.yml
In the https://circleci.com/gh/ministryofjustice/cla_public/427 build, our tests failed with the message
```
ImportError: No module named ext.script
Exited with code 1
```
After investigating the cause, we saw that the installation of dependencies were unsuccessful, but the job step was still green, meaning `pip install` still exited with a 0 status.
This change will force the installation to exit with a non-zero status if broken dependencies are detected:
```
cla_public$ pip check
flask 1.0 has requirement Jinja2>=2.10, but you have jinja2 2.7.3.
flask 1.0 has requirement Werkzeug>=0.14, but you have werkzeug 0.9.6.
cla_public$ echo $?
1
```
=> Check dependency integrity after installation

.circleci/config.yml
Push the built Docker image to both DSD and ECR Docker registries.
Unfortunately, using the DSD registry forces us to lock everything to Docker 17.03 where we want to use those images, which is proving to be a blocker.
In order to remove that constraint, we chose to push the built image into both Docker registries.
=> Push to both DSD and ECR Docker registries

.circleci/config.yml
Changes how timezones are checked to be more robust.
It is not guaranteed that the `/etc/localtime` file will stay symlinked. We could also copy the original timezone file and the behaviour would still be the same, but the test would fail.
This changeset proposes an alternative test for this behaviour, based on the default format of the `date` command:
```
Fri Feb  2 12:32:42 GMT 2018   # During winter
Tue Aug 28 14:02:43 BST 2018   # During summer
```
Since the command displays the abbreviated name of the timezone, we can match on those abbreviations.
Notes:
- `GMT` stands for Greenwich Mean Time
- `BST` stands for British Summer Time
=> Check time in a system agnostic way

.circleci/config.yml
Changes the deployment so we deploy `branch_name.7_char_git_sha`.
Our current operational model is:
- Build, tag and push Docker images in the `build` CI job
- Deploy the `repo:$CIRCLE_SHA1` Docker image to Kubernetes
Ultimately, it would be nice if we could avoid pushing the `$CIRCLE_SHA1` Docker tags to the repository for feature branches. This is because these references are superseded by the `master` build once the feature branch is merged.
Because they are superseded, we do not have to keep them around after the merge happens. Since our "Maximum number of images per repository" is 1000, we want to delete old, unnecessary tags.
We cannot _easily_ delete tags that are git SHA references, as we have no easy way to match and delete them.
In contrast, it's easy to set up a lifecycle …
=> Deploy Docker image digest instead of Docker tags

Dockerfile
This reverts commit 5cce3b76ad105c6bf1b9acd186e979bcba5da5a3, as it broke the service:
```
File "/usr/local/lib/python2.7/dist-packages/extended_choices/__init__.py", line 6, in <module>
from setuptools.config import read_configuration
ImportError: No module named config
```
The version installed by `apt-get` is too low and I seem to have misinterpreted the installation messages. I thought they meant nothing happens but in reality all of those packages were upgraded.
=> Revert "Remove redundant install of pip, wheel, setuptools"

.circleci/config.yml, README.md, kubernetes_deploy/staging/deployment.yml
Adds staging-deploy to CircleCI behind a manual approval step.
This has been mostly copied from the [laa-fee-calculator](https://github.com/ministryofjustice/laa-fee-calculator) project.
📝 We are using `kubectl` commands to deploy into staging environment before `helm` because it's quicker to implement. The intention is to use Helm in the future.
Pairing with: @sldblog
To make `kubectl config use-context staging` work, we had to create a `circleci` `ServiceAccount` in https://github.com/ministryofjustice/cloud-platform-environments/pull/140 and create the following environment variables in CircleCI:
- `KUBE_ENV_STAGING_CACERT`
- `KUBE_ENV_STAGING_NAME`
- `KUBE_ENV_STAGING_NAMESPACE`
- `KUBE_ENV_STAGING_TOKEN`
This is documented in …
=> Add staging-deploy to CircleCI

cla_public/apps/base/views.py, cla_public/config/common.py
This pull request redirects the route `/` to https://www.gov.uk/check-legal-aid, the GOV.UK start page for Civil Legal Advice.
It is not possible to change the link in the header directly because it is buried inside `base.jinja` template, which lives inside the `jinja-moj-template` package.
None.
=> LGA-192 Add redirect to gov.uk start page

README.md, cla_public/config/common.py, cla_public/config/docker.py, cla_public/config/testing.py, kubernetes_deploy/staging/deployment.yml
- Consolidates how [laalaa](https://github.com/ministryofjustice/laa-legal-adviser-api/) and [backend](https://github.com/ministryofjustice/cla_backend) are configured.
- Changes Flask logging inside Docker containers to use the default "console" output.
- Amends the Kubernetes staging deployment to reflect the new configurations.
Currently, configuring the `cla_backend` and `laa-legal-adviser-api` URLs is not straightforward.
The backend can be configured through `BACKEND_API` or `BACKEND_BASE_URI` or `CLA_BACKEND_PORT`, depending on the environment.
The legal adviser API can be configured through `LAALAA_API_HOST` or `LAALAA_PORT`, depending on the environment.
This changeset consolidates so that all environments can be configured via:
- `BACKEND_BASE_URI` environment variable for the …
=> Consolidate configuration

.circleci/config.yml, .circleci/define_build_environment_variables, .circleci/deploy_to_staging, .circleci/notify_slack_channel, .circleci/tag_and_push_docker_image
Adds a notification to our Slack channel about deployments. For now, only _staging_ deploys are supported.
Docker builds and deployments share a lot of environment variables. One way would be to redefine all the variables. Another would be to reuse the definitions.
We took the approach of reusing the definitions from a shared shell script which is `source`d into all CI scripts.
Moving the scripts to files has a side-effect of the deployment script showing only this output:
```
$ #!/bin/bash -eo pipefail
.circleci/deploy_to_staging
deployment.extensions "laa-cla-public" configured
service "laa-cla-public" unchanged
ingress.extensions "laa-cla-public" unchanged
```
This information is not useful enough to see _what_ was deployed. We extended the deploy script with an explicit message about …
=> Notify Slack channel on deployments

kubernetes_deploy/production/deployment.yml, kubernetes_deploy/staging/deployment.yml
This pull requests configures Kubernetes to use liveness-probe to determine the health of the application.
The liveness probe will return a success if the application end point `ping.json` responds with a 200. If it doesn't, Kubernetes will attempt to restart the container. 
I have also set replicas to 2 for `staging` and 3 for `production`. This is [Kerin's comment](https://mojdt.slack.com/archives/CACTAK5FG/p1538486123000100) on why 3 is a good number:
>Yep default is one - personally I’d recommend 3, so you can still tolerate a failure during a deployment
>That also matches the number of AZs in AWS Ireland, and your containers will get spread across them evenly
By having pod replicas, Kubernetes will not terminate a running pod until deployed containers are running and ready, as deemed …
=> LGA-284 Configure Kubernetes to use HTTP liveness-probe

cla_public/config/common.py
Set custom working hours to match Operator Service's reduced hours on Christmas Eve and New Year's Eve 2018.
See accompanying changes in related repos:
- [cla_backend#488](
https://github.com/ministryofjustice/cla_backend/pull/488)
- [cla_common/call_centre_availability/__init__.py#L173](https://github.com/ministryofjustice/cla_common/blob/0.2.7/cla_common/call_centre_availability/__init__.py#L173)
=> LGA-380 Custom working hours for 2018-12

cla_public/apps/checker/tests/test_review_page.py
Clear up warnings in test output by explicitly declaring parser. `html.parser` is the implicitly chosen value.
=> Explicitly declare BeautifulSoup parser

kubernetes_deploy/production/deployment.yml, kubernetes_deploy/staging/deployment.yml
I have been introduced to the alertmanager.apps.cloud-platform-live-0.k8s.integration.dsd.io service which lets us filter alerts by the labels in Kubernetes.
To make filtering easier, I added three new labels:
- `env` for labelling the environment without having to filter for the namespace
- `service_area` for searching for all applications without our service area
- `service_team` to examine applications belonging to a single service team
None.
Example query: https://alertmanager.apps.cloud-platform-live-0.k8s.integration.dsd.io/#/alerts?silenced=false&inhibited=false&filter=%7Bnamespace%3D%22laa-cla-public-staging%22%7D
It's also possible to filter for `app="laa-cla-public-app"` now. Following these changes, we will be able to filter for `service_team="cla-fala"` as well.
=> Add environment, service area and team labels

docs/releasing.md
We need to remember to deploy to both environments while the split between template-deploy and Kubernetes is running.
This change mentions this in the deployment readme.
None.
=> LGA-350: Add warning message about split deployments

kubernetes_deploy/production/deployment.yml
This variable missing does not cause any errors on booting up the application, so we did not detect it before.
As we now have 10% traffic over to Kubernetes, quickly adding `GA_ID` environment variable to the production Kubernetes configuration.
None.
=> LGA-457: Add Google Analytics ID to Kubernetes

cla_public/libs/tests/test_utils.py, cla_public/libs/utils.py
- Fix `category_id_to_name` to expect a single unexpanded category.
- Add a simple covering test.
=> LGA-450 Fix map with previously assigned lambda and add simple test

.circleci/deploy_to_kubernetes, kubernetes_deploy/production/deployment.yml, kubernetes_deploy/staging/deployment.yml
Automatically annotate the deployments caused by CircleCI so we can see the rollout history:
```
$ kubectl rollout history deployment/laa-cla-public --namespace=laa-cla-public-production
deployment.extensions/laa-cla-public
REVISION  CHANGE-CAUSE
1         <none>
2         <none>
3         https://circleci.com/gh/ministryofjustice/cla_public/960
```
The intention is to easily identify why deployments happened and link back to the job that caused the rollout.
Reference: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#checking-rollout-history-of-a-deployment
Added `-o pipefail` to the shebang. If any of the `kubectl set` or `kubectl annotate` commands fail, we should fail the deployment.
Example: https://circleci.com/gh/ministryofjustice/cla_public/964 was green, …
=> Annotate deployments with change-cause

docs/releasing.md
Add instructions for rolling back on both of our deployments.
[Fancy diff link](https://github.com/ministryofjustice/cla_public/pull/798/files?short_path=f5758d3#diff-f5758d353c2bb60f873830856c7ce6e0).
None.
=> LGA-464: Document rolling back to previous versions

.circleci/config.yml, Dockerfile
On CircleCI, the `test` jobs are currently failing: [example 1](https://circleci.com/gh/ministryofjustice/cla_public/992), [example 2](https://circleci.com/gh/ministryofjustice/cla_public/994), [example 3](https://circleci.com/gh/ministryofjustice/cla_public/996).
https://www.python.org/dev/peps/pep-0517/ causes problems with `cla_common` and pip 19 uses it by default.
Using `--no-use-pep517` does not work with `pip install -r requirements.txt`. The workaround is to downgrade to the previous version of pip.
We can upgrade to the next `pip` version if `cla_common` is made compatible with https://www.python.org/dev/peps/pep-0517/.
@farrepa @said-moj @Katy600 Is the above statement correct?
=> Use 18.1 pip version

docs/releasing.md
This pull request removes documentation about the template-deploy environment.
We have switched to Kubernetes (provided by the Cloud Platform team at MoJ Digital), which means we no longer need the previous environment.
None.
=> LGA-481: Remove template-deploy from documentation

.circleci/config.yml, .circleci/tag_and_push_docker_image
We are 100% on Kubernetes! ~~(Well, not _yet_, but it will be applied today.)~~
We no longer need to deploy on template-deploy, so we no longer need to build for the Docker registry used by that environment.
This pull request removes the use of the old registry.
The change speeds up the Docker build job by about 2.5 minutes (7 minutes 50 seconds &rarr; 5 minutes 10 seconds).
=> LGA-481: Remove template-deploy Docker registry from build

.circleci/define_build_environment_variables, .circleci/deploy_to_kubernetes, docs/kubernetes.md
Please read the below description then review commit-by-commit.
This pull request changes the deployment scripts to match the deployment instructions and adds further setup steps to make the deployment reproducible on local machines.
The documentation related to deployment did not mention that Kubernetes namespaces have to be defined. On CircleCI, the namespace is set in the [`setup-kube-auth`](https://github.com/ministryofjustice/cloud-platform-tools-image/blob/006d7cf8ad332bc21c7aaa996595f8cd926ac1be/circleci/setup-kube-auth#L28-L31) script, but they do not work locally.
The deployment instructions now explicitly mention namespace setup.
Despite the deployment guide's instructions, `.circleci/deploy_to_kubernetes` does not **only** require an `ECR_DEPLOY_IMAGE` environment variable but …
=> LGA-481: Match deployment process to documentation

.circleci/config.yml, cla_public/apps/contact/fields.py, cla_public/config/common.py, cla_public/config/local.py.example, cla_public/config/operating_hours.py, cla_public/config/testing.py, docs/installation.md
Currently, it’s possible for the application to be deployed without having
- SMTP (confirmation e-mail) configuration
- Zendesk (feedback) configuration
- Sentry (exception monitoring) configuration
This leads to application silently failing to do any of the above tasks.
This PR prevents the application starting up without those configurations
It seems the debug toolbar extension is registered when DEBUG is True. Also having the `EXTENSIONS.append(DebugToolbarExtension())` in the local.py was causing app to fail complaining about the view method already being registered. I have commented this snippet out
The opening hours config was moved to a separate config file as this is required before the flask app has been created. The previous method was getting the open hours settings directly …
=> LGA-497 - Stop application from booting up without essential configuration

README.md
Fixes the link in README that _should_ point to your kubernates doc.  
Not at this time.
=> Fix link to kubernetes.md

.circleci/config.yml
Allows forked pull requests to build Docker images without pushing.
The end goal is a workflow that runs all the tests but does not produce testable artefacts. I think this is a workable state for public contributions.
The `$CIRCLE_PR_NUMBER` environment variable is only populated on forked pull requests. (https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project)
Using this behaviour we can split the control flow of the Docker build step to build and test the Docker image, but do not attempt to login and push.
Initially, I wanted to separate the jobs to (`docker-build` and `docker-push`) but then I realised making the image built in the first job available for the second job would not be trivial, so I lazied out.
=> Allows forked pull requests to build Docker images

cla_public/app.py, cla_public/config/common.py, cla_public/middleware.py, requirements/base.txt
statsd is not required as we have instrumentation in Kubernetes for free. This PR remove statsd monitoring code from the code base
=> LGA-498 - Remove legacy statsd as those stats are provided by kubernetes

cla_public/templates/checker/result/face-to-face.html
Explicitly sets postcode redacted title and location for GA before pageview send
=> LGA-47 Redact postcode from GA title and location before pageview send

cla_public/templates/macros/subform.html
Add `autocomplete="tel"` and `type="tel"` to `contact_number` input fields.
This is to fix "callback requests are being received with no phone number recorded against the case".
=> LGA-422 Set autocomplete and type attributes on contact_number input

kubernetes_deploy/production/ingress.yml, kubernetes_deploy/staging/ingress.yml
Enable TLS in the Ingress resource by adding a new certificate resource.
This was implicitly been done by the cloud platforms team before however recent changes mean that we need to explicitly do this.
The circleci service account needed extra permission to be able to create the certificate resource which was cover in this PR https://github.com/ministryofjustice/cloud-platform-environments/pull/501
=> LGA-529 - Enable TLS using new cloud platform spec

cla_public/templates/errors/5xx.html
[LGA-487 Service offline page when CLA Public can't communicate with CLA Backend API](https://dsdmoj.atlassian.net/browse/LGA-541l)
- It edits the service offline pages with new content if the backend is down, to alert users appropriately and guide them on their alternative options.
I was able to check that this service offline page was being displayed by:
- setting DEBUG = False
- running cla_public with out backend
- placing a '/start' at the end of the url generated in the terminal when run locally. 
=> LGA-487 Edit service down page that shows when cla backend api is down

docs/installation.md
The sensible defaults provided in https://github.com/ministryofjustice/cla_public/pull/807 have to be used for local development if no env variables are going to be required.
There is a ticket in refactoring this to match the way that this done on fala https://github.com/ministryofjustice/fala/pull/29/files
=> Update Read me to use config/local.py for local setup

cla_public/libs/laalaa.py, cla_public/libs/tests/test_laalaa.py
- Add an iterable default for categories
- Test `count` key included in results
- Test searching with no categories
- Test results are merged
=> LGA-579 Tests and iterable default categories

cla_public/apps/contact/forms.py, cla_public/apps/contact/views.py
- Adds a max length validator to the `other_adaptation` field of the contact form, which is ignored if the `is_other_adaptation` field is false
- Removes the `optional` validator from the `adaptations` ValidatedFormField, as that was short-circuiting validation on the form
- Removes the value of `other_adaptation` from the form and from the session if `is_other_adaptation` is false
As the value of other_adaptation is (rightly) not validated if is_other_adaptation is false, we can end up passing very long values to the back end still (if the user fills in the field and then unticks the box to hide and ignore that field), and it's the use of these in the session which appears to cause the session to break, leading to the server error. Therefore, we now remove the value if …
=> LGA-551 Make contact form resilient to long free text input

cla_public/templates/checker/result/confirmation.html, cla_public/templates/checker/result/face-to-face.html, cla_public/templates/checker/result/ineligible.html, cla_public/templates/scope/ineligible.html, cla_public/templates/scope/mediation.html
-- adds a link to feedback survey where it was missing 
-- replaces links to survey with GDS link style
-- adds a finish button to the confirmation page, instead of the survey banner, so user can exit the service
-- adds GA tracking to the finish button to monitor responses
I couldn't get the GA tracking to work on the staging site, so I'll have to check the configuration is sending events to analytics on the live site.
Relates to Jira tickets #599 and #603
=> LGA-599 & LGA-603 Feedback position

cla_public/templates/emails/confirmation.txt
This PR updates the confirmation.txt file with the feedback survey link. The email is triggered when someone adds an email address on the callback page or confirmation page.
None.
This relates to ticket LGA-597.
Image of how the email looks when triggered is attached.
=> LGA-597 - adding feedback link to emails

README.md
Our new hires in another team in the service area have highlighted that it is hard to find something related to an application unless we know where to look.
One of the ideas to deal with this difficulty is to make the application Readmes the starting point for everything.
In the above spirit, this pull request introduces new badges that will link directly to:
- Where to find the application runbook.
- Where to find the runtime exceptions.
- Where to find the runtime logs.
- Where to find the feature tests.
- Where to find the continuous integration system, with a representation of the latest production build.
Not at this time.
=> Add badges with links to relevant pages

kubernetes_deploy/development/deployment.yml, kubernetes_deploy/staging/deployment.yml
Configures `staging` and `development` deployments of the site to use the new domain for the staging instance of the legal adviser API, which is the kubernetes-deployed version.
=> LGA-587 - Update LAALAA_API_HOST env var on dev and staging pods

cla_public/templates/checker/about.html, cla_public/templates/checker/additional-benefits.html, cla_public/templates/checker/benefits.html, cla_public/templates/checker/income.html, cla_public/templates/checker/outgoings.html, cla_public/templates/checker/property.html, cla_public/templates/checker/result/confirmation.html, cla_public/templates/checker/result/eligible-f2f.html, cla_public/templates/checker/result/eligible.html, cla_public/templates/checker/result/face-to-face.html, cla_public/templates/checker/result/ineligible.html, cla_public/templates/checker/review.html, cla_public/templates/checker/savings.html, cla_public/templates/checker/time-out-warning.html, cla_public/templates/contact.html, cla_public/templates/cookies.html, cla_public/templates/feedback-confirmation.html, cla_public/templates/feedback.html, cla_public/templates/interstitial.html, cla_public/templates/online-safety.html, cla_public/templates/privacy.html, cla_public/templates/reasons-for-contacting.html, cla_public/templates/scope/diagnosis.html, cla_public/templates/scope/ineligible.html, cla_public/templates/scope/mediation.html
This adds text at the bottom of key pages in the user flow warning users that their session expires after 30 minutes of inactivity.
This is related to ticket LGA-584
https://dsdmoj.atlassian.net/browse/LGA-584
=> LGA-584 Time out warning

cla_public/templates/checker/about.html, cla_public/templates/checker/additional-benefits.html, cla_public/templates/checker/benefits.html, cla_public/templates/checker/income.html, cla_public/templates/checker/outgoings.html, cla_public/templates/checker/property.html, cla_public/templates/checker/result/confirmation.html, cla_public/templates/checker/result/eligible-f2f.html, cla_public/templates/checker/result/eligible.html, cla_public/templates/checker/result/face-to-face.html, cla_public/templates/checker/result/ineligible.html, cla_public/templates/checker/review.html, cla_public/templates/checker/savings.html, cla_public/templates/contact.html, cla_public/templates/cookies.html, cla_public/templates/errors/404.html, cla_public/templates/errors/4xx.html, cla_public/templates/feedback-confirmation.html, cla_public/templates/feedback.html, cla_public/templates/index.html, cla_public/templates/interstitial.html, cla_public/templates/laalaa.html, cla_public/templates/online-safety.html, cla_public/templates/privacy.html, cla_public/templates/reasons-for-contacting.html, cla_public/templates/scope/diagnosis.html, cla_public/templates/scope/ineligible.html, cla_public/templates/scope/mediation.html, cla_public/templates/session-expired.html
The end-to-end tests have been broken for a while due to timeout changes introduced in https://github.com/ministryofjustice/cla_public/pull/851
This PR adds a .page-title class to the `<h1>` tags that contain the page title so the tests can match for those with class selectors
https://github.com/ministryofjustice/laa-cla-e2e-tests/pull/62 - PR for end-to-end tests that uses the changes introduced in this PR
=> LGA-709 - Add page-title class to h1 that have the page title

cla_public/apps/contact/fields.py
To fix the display issue of the front end splitting the string into
individual letters because it's expecting an iterable of messages.
Required.
=> LGA-753 - fix validation error message for invalid time slot

cla_public/templates/checker/about.html, cla_public/templates/scope/diagnosis.html
Adds the following warning to the scope diagnosis and means checker pages when viewed in Edge
=> LGA-767 - Add warning message in Edge

cla_public/templates/cookies.html
Updates the cookie list to show all cookies that we use on the service
I've tidied up the wording in places to reference our service rather than generic GOV.UK cookie policies.
LGA-369
https://dsdmoj.atlassian.net/browse/LGA-369
=> LGA 369 update cookies

cla_public/apps/checker/tests/test_interstitial.py, cla_public/apps/checker/views.py
Adding violence, education, debt and discrimination to list of categories to show laalaa link
Required.
=> LGA-788 - Adding FALA routes through CLA for Education and Discrimination categories

cla_public/apps/base/constants.py, cla_public/apps/base/forms.py, cla_public/static-templates/errors/50x.html, cla_public/templates/_phase-tag.html, cla_public/templates/base.html, cla_public/templates/feedback.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po, cla_public/translations/messages.pot
This PR replaces the Survey Monkey feedback link in the header and the Zendesk link in the footer with the Contact CLA feedback route. This gives users a consistent way of getting help if they have a problem using the service.
This PR also includes changes to the feedback form (using zendesk) previously linked from the footer. We are proposing future changes to the feedback route and may use the changed form to capture details if users are experiencing technical issues with the service.
Related ticket is: https://dsdmoj.atlassian.net/browse/LGA-752
=> LGA 752 remove survey

cla_public/apps/base/forms.py, cla_public/apps/base/views.py, cla_public/apps/checker/views.py, cla_public/apps/contact/views.py, cla_public/libs/views.py, cla_public/static-src/javascripts/modules/form-errors.js, cla_public/templates/emails/zendesk-feedback.txt, cla_public/templates/feedback.html
Rewrites ajax form validation to be done on a POST request, rather than an OPTIONS request. Therefore the views have to be able to handle the ajax and non-ajax ways of handling page redirects and displaying errors.
In fixing the behaviour in Edge, we've had to completely change the views to use POST for the ajax request (rather than OPTIONS), so this doesn't just affect Edge, where the view were already not working, but all browsers.
Impacts the following paths, with javascript enabled and disabled:
- `/feedback`
- `/reasons-for-contacting`
- `/result/eligible`
- `/result/provisional`
- `/result/confirmation`
- `/contact`
- `/about`
- `/benefits`
- `/additional-benefits`
- `/property`
- `/savings`
- `/income`
- `/outgoings`
- `/review`
Shouldn't need testing in more than one browser on …
=> LGA-751 Fixing form submitting on Edge browser

cla_public/apps/checker/constants.py, cla_public/libs/laalaa.py, cla_public/libs/tests/test_laalaa.py, requirements/base.txt
Fetch LAALAA provider categories from LAALAA endpoint instead of a local constant in this app
Requires https://github.com/ministryofjustice/laa-legal-adviser-api/pull/137 to be LAALAA master before merging in this PR
https://dsdmoj.atlassian.net/browse/LGA-848 has been created to capture the relationship between CLA and LAALAA categories of law with the aim of working with business to see if we can also consume CLA categories from LAALAA and to also understand the relationship and difference of CLA and LAALAA categories of law.
=> LGA-813 -  Fetch LAALAA provider categories from LAALAA endpoint

kubernetes_deploy/production/deployment.yml
Start using Kubernetes cloud platform hosted LAALAA_API_HOST for production
=> LGA-634 - Start using Kubernetes cloud platform hosted LAALAA_API_HOST for production

README.md
Removes the mention of discrimination and education in the readme.
The recent legislation changes have removed the need to go through the "Gateway" for Education and Discrimination categories of law.
I noticed this while preparing a presentation that link to this readme.
=> Remove education and discrimination from the readme

cla_public/templates/checker/about.html, cla_public/templates/scope/diagnosis.html
Remove Edge warning on cla_public
Reverts https://github.com/ministryofjustice/cla_public/pull/859
=> LGA-803 - Revert "LGA-767 - Add warning message in Edge"

.circleci/config.yml
Uses a new laa-cla-public-live-0 context for the existing build and deploy steps (which currently only get their env vars from the project settings). This will allow us to move live-0-specific env vars out of the project settings, stopping them affecting the live-1 flow when we get to it and meaning we won't have to override or unset those env vars.
=> Use laa-cla-public-live-0 context for build and deploy

cla_public/apps/checker/constants.py, cla_public/apps/checker/session.py, cla_public/apps/checker/tests/test_payloads.py, cla_public/apps/contact/forms.py, cla_public/apps/contact/tests/test_mail.py, cla_public/apps/contact/views.py, cla_public/templates/emails/confirmation.txt, cla_public/templates/macros/subform.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po, cla_public/translations/messages.pot, requirements/base.txt
- Remove 'Is it safe for us to leave a message on this number?' fields from 'call me back' and  'Call someone else instead of me' forms
- Remove voice messages text from email templates
- Send SAFE value in safe_to_contact field to the backend when user has requested a callback
We have decided to remove this field due to receiving complaints from end user about not getting voice messages and the call centre provider not being allowed to leave voice messages
=> LGA-809 - Remove 'Is it safe for us to leave a message on this number?' fields from contact forms

cla_public/apps/contact/fields.py, cla_public/config/common.py, requirements/base.txt
Use OPERATOR_HOURS from cla_common
=> LGA-892 - Use OPERATOR_HOURS from cla_common

kubernetes_deploy/production/ingress.yml, kubernetes_deploy/production_live_0/ingress.yml
Adds the live production hostname to the live-1 ingress
Removes the live production hostname from the live-0 ingress
=> LGA-701 - production live-1 cutover

manage.py, requirements/base.txt, requirements/test.txt
* LGA-873 - Remove MockServer from manage.py
The MockServer was a relic from when we used to have nightwatchjs tests run by jenkins
The nightwatchjs end-to-end tests has been moved to https://github.com/ministryofjustice/laa-cla-e2e-tests repo
Moved Flask-Script package from test requirements to production requirements because the package is used in manage.py to register additional commands
=> LGA-873 - Remove MockServer from manage.py

cla_public/apps/checker/tests/test_review_page.py, cla_public/templates/checker/review.html, cla_public/templates/macros/review.html, cla_public/translations/cy/LC_MESSAGES/messages.po
Part of frontend changes stage 3.  This changes the review answers pages to a standard GDS pattern.  
The links to change answers now (with some exceptions) lead directly to the question rather than just the page.  This is especially useful for longer pages.  
The exceptions are the early questions, where the process is unchanged.
=> LGA-901 - Check Your Answers (CYA) Screen

cla_public/static-src/javascripts/modules/form-errors.js, cla_public/static-src/javascripts/modules/label-focus.js, cla_public/static-src/javascripts/modules/label-select.js, cla_public/static-src/stylesheets/main.scss, cla_public/templates/checker/about.html, cla_public/templates/contact.html, cla_public/templates/macros/form.html, cla_public/templates/macros/subform.html
Changes input boxes to the GDS standard:
- Text input
- Integer input (how many dependants etc)
- Text areas
- Currency input
- Drop-down lists
Tickboxes on Contact page now use the new style - they needed the changes from this ticket to be changed because of the pop-up questions.
Immediate risk of harm styling has been changed.
=> LGA 872 input boxes

cla_public/apps/scope/api.py, docker/local_deploy.sh
Uses the new, untranslated, 'key' key from the API response when determining the category. This prevents the lookup from failing when passed a step name in Welsh.
Improves the local k8s script by adding deletion of deployments, so that this doesn't need to be run separately.
Requires https://github.com/ministryofjustice/cla_backend/pull/610
=> Use 'key' from nodes, rather than 'label', when calculating category

cla_public/config/common.py, cla_public/config/deployment.py, cla_public/templates/checker/result/eligible-f2f.html, cla_public/templates/checker/result/face-to-face.html, cla_public/templates/laalaa.html, kubernetes_deploy/production/deployment.yml, kubernetes_deploy/staging/deployment.yml
Adds Google Maps API Key so that the development watermark is not shown on the map
=> LGA-685 - Adding Google Maps Api Key

cla_public/static-src/stylesheets/_tables.scss, cla_public/templates/checker/income.html, cla_public/templates/checker/outgoings.html, cla_public/templates/checker/result/eligible-f2f.html, cla_public/templates/checker/result/eligible.html, cla_public/templates/checker/result/ineligible.html, cla_public/templates/cookies.html, cla_public/templates/feedback-confirmation.html, cla_public/templates/feedback.html, cla_public/templates/laalaa.html, cla_public/templates/macros/element.html, cla_public/templates/macros/form.html, cla_public/templates/online-safety.html, cla_public/templates/privacy.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po, cla_public/translations/messages.pot
Changes all headings and paragraphs to use new GDS classes.
Tidies up other HTML errors - such as adding table summaries
Rationalises the abbreviation tags, especially in Welsh.
Updated a radio button field on the feedback page that had been missed.
Updated contact address at PF to omit the floor and office number and add in LAA.
=> LGA-924 HTML and CSS cleanup

.circleci/config.yml, .coveragerc, .gitignore, README.md, cla_public/apps/base/tests/__init__.py, cla_public/apps/base/tests/test_healthchecks.py, cla_public/apps/base/tests/test_locale.py, cla_public/apps/base/tests/test_reasons_for_contacting.py, cla_public/apps/checker/tests/test_api_already_saved_error.py, cla_public/apps/checker/tests/test_api_timeout.py, cla_public/apps/checker/tests/test_cait_intervention.py, cla_public/apps/checker/tests/test_form_config.py, cla_public/apps/checker/tests/test_integration.py, cla_public/apps/checker/tests/test_means_test.py, cla_public/apps/checker/tests/test_payloads.py, cla_public/apps/checker/tests/test_validation.py, cla_public/apps/contact/tests/test_availability.py, cla_public/apps/contact/tests/test_notes.py, cla_public/apps/geocoder/tests.py, cla_public/apps/scope/tests/test_diagnosis_api.py, cla_public/libs/tests/test_views.py, manage.py, requirements/test.txt
- Wraps test running in coverage
- Stores the output on circleci as artifacts
- Sends coverage results to coveralls.io
- Adds a coveralls badge to the readme
- Swapped test runner from nosetests to unittest-xml-reporting to generate xml result files to be used by circleci
- Generates and stores test metadata in xml format for CircleCI to monitor
- Added a tearDown method to cleanup after tests that create a temporary flask app and use app.test_request_context. If this is not done then the flask will raise an AssertionError: Popped wrong request context.
Similar to https://github.com/ministryofjustice/cla_backend/pull/583
=> LGA-695 - Add test coverage to project

cla_public/templates/checker/result/_find-legal-adviser.html, cla_public/templates/checker/result/eligible.html, cla_public/templates/checker/result/ineligible.html, cla_public/templates/contact.html, cla_public/templates/cookies.html, cla_public/templates/macros/element.html, cla_public/templates/macros/help-orgs.html, cla_public/templates/scope/ineligible.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po
Stopped links opening in new tabs by writing another macro `link_same_window()`.  
Kept old `link_new_window()` macro to be used if needed in future.
Removed newline from macro to remove trailing space from link when on page.
=> LGA-832 Stopped links opening in new tabs

cla_public/config/common.py, cla_public/libs/call_centre_availability.py, requirements/base.txt
Use Flasks current_app.cache to cache bank holidays
Requires https://github.com/ministryofjustice/cla_common/pull/91
cla_common.call_centre_availability.BankHolidays now has a pluggable cache factory which was introduced in https://github.com/ministryofjustice/cla_common/pull/91
https://github.com/ministryofjustice/cla_common/pull/91
=> LGA-973 - Use Flasks current_app.cache to cache bank holidays

cla_public/static-src/javascripts/modules/cookie-banner.js, cla_public/static-src/javascripts/modules/cookie-settings.js, cla_public/static-src/javascripts/modules/google-analytics.js, cla_public/templates/_cookie-consent-form.html, cla_public/templates/_cookie-popup.html, cla_public/templates/base.html, cla_public/templates/checker/result/face-to-face.html
Rename brexit cookie policy to gds (was mislabelled previously)
Trigger pageview event cookie consent
=> LGA-1008 - Trigger pageview event cookie consent

.circleci/config.yml, Dockerfile, docs/development.md, docs/installation.md, requirements/base.txt, requirements/no-deps.txt
- Requires https://github.com/ministryofjustice/cla_public/pull/917
- Remove django dependecy
The package jinja-moj-template is no longer being maintained and has a dependency on django >= 1.3 so that it can use the static helper in it's template file.  However a mimic for this has already been added (see cla_public/django_to_jinja.py) for the flask app. So this package can be used without django.
To remove this package dependency on the old version of django I have created a no-deps.txt requirements file, that should install it without also installing django
=> LGA-945 - Remove django dependecy

cla_public/static-src/stylesheets/main.scss, cla_public/templates/base.html
Adds a quick escape button to the service for certain routes:
- Javascript only
- When displayed, always visible
- Fires of a GA function
- Replaces current tab with google and opens BBC weather in a new tab
=> LGA-1082 quick escape button

cla_public/static-src/stylesheets/main.scss
Changed the CSS so the input box was "above" the £ sign and so was receiving the focus when the pound sign was clicked on.  
=> LGA-1074 Amended CSS for currency input

cla_public/templates/errors/5xx.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po
Changes all instances of the number 78900 back to 80010.  
This reverts [PR 932](https://github.com/ministryofjustice/cla_public/pull/932/files).  
=> LGA-1123 changed text number back to 80010 from 78900

cla_public/static-src/javascripts/govuk.main.js, cla_public/templates/base.html
Uses the govuk-frontend polyfill for IE and Edge to fix the details dropdown bug.
Govuk-frontend was already installed, but the javascript part of the package needed to be included in the compiled javascript for it to work.
Mentions:
I used var in the 'govuk.main.js' file due to the fact that one of the plugins for webpack doesn't support ES6. The specific plugin is 'UglifyJsWebpackPlugin' and may need another ticket to look into possibly updating it. One of the new versions to look into is called TerserWebpackPlugin.
=> LGA-1107 Details tag not working in IE & Edge

.circleci/config.yml, .circleci/define_build_environment_variables, .circleci/tag_and_push_docker_image, .dockerignore, .gitignore, Dockerfile, bin/delete_staging_release.sh, bin/local_deploy.sh, bin/production_deploy.sh, bin/staging_deploy.sh, bin/staging_multideploy.sh, helm_deploy/cla-public/.helmignore, helm_deploy/cla-public/Chart.yaml, helm_deploy/cla-public/templates/NOTES.txt, helm_deploy/cla-public/templates/_helpers.tpl, helm_deploy/cla-public/templates/dashboard.yml, helm_deploy/cla-public/templates/deployment.yaml, helm_deploy/cla-public/templates/ingress.yaml, helm_deploy/cla-public/templates/service.yaml, helm_deploy/cla-public/templates/tests/test-connection.yaml, helm_deploy/cla-public/values-dev.yaml, helm_deploy/cla-public/values-production.yaml, helm_deploy/cla-public/values-staging.yaml, helm_deploy/cla-public/values.yaml
Creates a Helm chart and uses it when deploying to staging on CircleCI
If the branch is `master`, the release has the name `cla-public`. Otherwise, its name is generated from the branch name and is thus for that branch only.
Leaves the production deploy unchanged
The master branch staging deploy does not currently create an `Ingress`, as this would clash with the non-Helm `Ingress`. The existing one can be manually edited to point to the new Helm `service`, and then the deploy modified to define the `Ingress` after that.
=> LGA-1085 - Helm deploys for staging

bin/production_deploy.sh
Enables the Helm ingress
Currently based on the branch that introduces the production Helm deploy, for simpler diff. That will merge and then this will follow it into `master`
=> LGA-1163 - Enable production ingress

cla_public/templates/base.html
Added condition so quick exit only fires when quick exit enabled (checks for class)
=> LGA-1158 Escape key activates quick exit only when quick exit visible

cla_public/templates/base.html
New JS to hide unwanted days and times.  Done by matching the text in the options.  
Also function to disable "call today" on a weekend.  
To be reversed once LGA-1053 is complete
=> LGA-1181 COVID-19 opening times changed by JS function

cla_public/templates/base.html, requirements/base.txt
Uses the updated cla_common library to reduce the callback time options to reflect the new operator hours.
Removes the temporary js fix to the problem
Pins to version rather than commit hash, as the intent is clearer.
Removes the version from the egg name, as it's not necessary.
=> LGA-1053 - Operator hours

cla_public/templates/base.html, helm_deploy/cla-public/values-production.yaml, helm_deploy/cla-public/values-staging.yaml
After switching to the welsh language, when navigating welsh pages, each page will send 'cy_GB' as the language code.
Adds Google Analytics credentials to Kubernetes to enable testing on production and staging. This was outside the scope of the ticket, but it was necessary in order to test my changes which is why it was included.
Sets the fallback English language code as 'en_GB' instead of en'.
=> LGA-1119 Change GA language field on Welsh site from en-gb to en-cy

.circleci/config.yml
Rearranges Circle CI flow so approval for staging deploy can be done immediately.
It also makes staging deploy require a successful build as well as the approval.
(Essentially, the requirement for Build is moved from the approval to the actual staging deploy.)
=> LGA-1213 Move Circle CI Staging Approval earlier

cla_public/apps/contact/tests/test_availability.py, cla_public/apps/contact/tests/test_mail.py, manage.py
The new test runner wasn't exiting with a non-zero exit code even when tests failed, so this makes it do so.
It also fixes the tests which broke when cla_common was upgraded to reflect the new operator hours
=> LGA-1230 - Fix always-passing-tests bug

helm_deploy/cla-public/values-dev.yaml, helm_deploy/cla-public/values-staging.yaml
Use cla_backend kubernetes staging deployment
backend_base_uri previosuly had the the trailing slash, the paths are passed with the leading slash this will results in the url becoming scheme://domain.tld//uri  which django will see it as a non-existing path and return a 404.
This is not happening on the current deployment system because nginx is sitting in front of uswgi and reconstructing the url.
=> LGA-1231 - Use cla_backend kubernetes staging deployment

helm_deploy/cla-public/values-dev.yaml, helm_deploy/cla-public/values-staging.yaml
Reverts ministryofjustice/cla_public#955
Seems to have broken translation. Need to investigate why this happens
=> Revert "LGA-1231 - Use cla_backend kubernetes staging deployment"

helm_deploy/cla-public/values-production.yaml
The new env var was intended to switch on Google Tag Manager but there
was a typo so it actually overrode (and therefore broke) the GA
implementation. This should restore both GA and GTM
=> LGA-1252 - Restore Google Analytics on production

helm_deploy/cla-public/values-production.yaml
Correctly sets up the Google Tag Manager snippet on production.
Surprisingly, the ID is the same across environments but the auth value
is what should differ.
=> LGA-1264 - Make production use the correct GTM environment

cla_public/apps/base/views.py, cla_public/templates/_resources.html, cla_public/templates/index.html
Disables the `/` redirect except on production
Updates the template served at `/` on non-production environments to match the gov.uk service landing page
Still needs some work on translations, both the translatable strings being marked for a couple of more involved cases, and the translations generated and filled in for everything else. This is being done in another PR, and this one should be fine to release with these limitations.
=> LGA-1017 - Non-prod landing page

helm_deploy/cla-public/values-staging.yaml
Use cla_backend kubernetes staging deployment
backend_base_uri previosuly had the the trailing slash, the paths are passed with the leading slash this will results in the url becoming scheme://domain.tld//uri which django will see it as a non-existing path and return a 404.
This is not happening on the current deployment system because nginx is sitting in front of uswgi and reconstructing the url.
Previously done at https://github.com/ministryofjustice/cla_public/pull/955 but then reverted out at https://github.com/ministryofjustice/cla_public/pull/959 due issues with translation (The staging environment was previously unstable as it wasn't using a persistent database backend)
=> Use Kubernetes CLA Backend staging as the backend for staging cla

cla_public/templates/index.html, cla_public/translations/cy/LC_MESSAGES/messages.po
Styles the internal start page similar to the start page on gov.uk
Adds in Welsh translations for the start page (taken from the main page on gov.uk)
=> LGA-1273 internal start page

cla_public/templates/scope/diagnosis.html, cla_public/translations/cy/LC_MESSAGES/messages.po
Added in a check for the no options error and changed the page title subtly so it can be known whether the check is working.
=> LGA-1298 Changed title for no options error situation

cla_public/static-src/stylesheets/main.scss, cla_public/templates/base.html, cla_public/templates/moj_template_base.jinja
Added sticky behaviour.
Adds in a non-visual element to the QE button for screen readers.
Moves the mobile button from the bottom to the top.
Adds a fallback for non-JS users.
Adds a border to the info bit.
=> LGA-1296 & 1297 QE accessibility

cla_public/apps/base/forms.py, cla_public/apps/base/views.py, cla_public/apps/checker/cait_intervention.py, cla_public/config/deployment.py
Fixes multiple checks that the `CLA_ENV` setting is the production setting
The value of the env var on kubernetes is "production" not "prod". This
was the case even before the recent changes to the kubernetes config
The homepage redirection was recently changed to check this setting, and
was incorrectly set based on the other uses, which appear to have been
wrong for a while.
=> LGA-1315 - Fix checks for CLA_ENV on production

cla_public/static-src/stylesheets/main.scss
The bug is a firefox-specific layout issue where the currency prefix is mis-aligned (vertically) with the input field.  The absolute positioning in Firefox is done after the padding, rather than ignoring padding as in other browsers.  
Added some Firefox-specific CSS to:
- position the currency correctly using a top value.
- add a white outline to the input box to catch any slight overflow from the positioning.
=> LGA-1319 CSS fix for Firefox bug

cla_public/apps/checker/forms.py, cla_public/apps/checker/validators.py
Allows `MoneyIntervalField` instances to be configured with different error messages for when they refer to the user's partner, and then to choose which messages to use when the sub-form is initiated.
Includes a sample set of `partner_` error messages, commented out.
Manually makes copies of the validators, as by default the validators will be the same instances even on different instances of the field (presumably due to the way they are copied when the form library initialises the form), so changing instance variables on them would affect the form instances in both halves of the form.
=> LGA-1283 - Partner error messages

cla_public/templates/checker/about.html, cla_public/templates/checker/additional-benefits.html, cla_public/templates/checker/benefits.html, cla_public/templates/checker/income.html, cla_public/templates/checker/outgoings.html, cla_public/templates/checker/property.html, cla_public/templates/checker/review.html, cla_public/templates/checker/savings.html, cla_public/templates/contact.html, cla_public/templates/feedback.html, cla_public/templates/macros/form.html, cla_public/templates/reasons-for-contacting.html
Amends the `actions()` function to allow an ID parameter, so the green button can be given an ID.  
=> LGA-1304 Add an ID to the green buttons

cla_public/static-src/stylesheets/main.scss, cla_public/templates/base.html
- removes the QE button from the tab order
- applies a CSS fix to make the QE info note (press escape) only appear when on non-mobile devices.
=> LGA-1327 quick exit tab order

cla_public/static-src/javascripts/modules/form-errors.js
Makes the ajax form submission use the form's `action` attribute as its
destination (instead of always just using the empty string)
This should fix forms which are set to POST do a url other than the one
they're currently on (eg /result/eligible posts to /contact)
Having this wrong was causing the ajax to POST to an endpoint that only
serves GET requests, and then the form would fall back to the submit
button's default behaviour of posting to the form action, so the user
was still continuing their journey but we were getting lots of warnings
from our back end.
=> LGA-955 - Fix `Unimplemented method POST` errors

cla_public/templates/base.html, cla_public/templates/checker/time-out-warning.html, cla_public/templates/scope/diagnosis.html
Added JS page reload for no-option instances.
Changed wording of no-options page to say "Loading..."
Added comment about reloading page for non-JS situations.
Changed GA naming so reports can be distinguished.
=> LGA-1170 no options bug

cla_public/apps/base/__init__.py, cla_public/apps/base/tests/test_extensions.py, cla_public/apps/base/views.py, cla_public/config/common.py, cla_public/templates/errors/5xx.html, cla_public/templates/maintenance.html, helm_deploy/cla-public/templates/deployment.yaml, helm_deploy/cla-public/values-dev.yaml, helm_deploy/cla-public/values.yaml
- Adds maintenance mode environment variable
- Adds a before_request action that when maintenance mode is enabled redirects **ALL traffic** to the /maintenance page.
When not in maintenance mode if someone goes to /maintenance then they will be redirected to /start
=> LGA-1347 Maintenance page

cla_public/templates/scope/diagnosis.html
Surrounds the merits choices with `<fieldset>` and the title is in a `<legend>`
=> LGA-1325 fieldset added to scope options

cla_public/static-src/javascripts/modules/find-legal-adviser.js, cla_public/static-src/stylesheets/_find-legal-adviser.scss, cla_public/templates/checker/result/_find-legal-adviser.html
Distance colour changed to black
Focus colour updated list of solicitors
Focus colour updated for the map controls and links
Map and Satellite buttons updated to mimic govuk buttons (not exactly the same colours to maintain suitable contrast with map)
Cat of law tags changed to a list at the bottom of the details bit
New JS to expand the size of the map to be more suitable to the list (avoiding double-scrolling).
Unused pagination controls bit hidden (dormant, can be resurrected if/when needed)
Max-width increased from 660 px to 960 px
=> LGA-1333 colours etc on map page

cla_public/static-src/stylesheets/_progress.scss, cla_public/static-src/stylesheets/_sidebar.scss, cla_public/static-src/stylesheets/main.scss, cla_public/templates/checker/_progress.html, cla_public/templates/macros/element.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po
Makes the your progress bit more accessible:
- Re-styles progress bar
- Removes links for current page
- Screen reader prefixes for all stages, including collapsed stages
- Removed old blue colour and replaced with govuk branding (or new environment colours)
=> LGA-1343 Your Progress

cla_public/templates/checker/_progress.html, cla_public/templates/checker/property.html, cla_public/templates/macros/form.html
Adds a property prefix so screen readers know that they are dealing with property number 1
- Sets a variable if property count > 1.
- Feeds variable into fieldset for all relevant fields.
- Radio buttons only, the currency fields pick up the fieldset legend.
=> LGA-1342 property prefixes

cla_public/static-src/javascripts/modules/form-errors.js, cla_public/static-src/stylesheets/_progress.scss, cla_public/templates/checker/base.html
Added "Error: " to the `<title>` tag when an error is thrown.  
JS and non-JS.
CSS tweak
=> LGA-1384 Error prefix for <title>

cla_public/apps/checker/forms.py, cla_public/static-src/javascripts/modules/find-legal-adviser.js, cla_public/templates/checker/result/_find-legal-adviser.html, cla_public/templates/checker/result/face-to-face.html, cla_public/templates/macros/form.html, cla_public/translations/cy/LC_MESSAGES/messages.po
LARP page
- If results are found, the whole page changes as opposed to just the map being shown. So the if statements now encompass most of the page rather than just the map section.  
- Most of the text from `face-to-face` has been moved into this structure in `find-legal-adviser`, after the map results bit.
- New titles, new text.
- New error messages, including tests for Crown Dependency postcodes.
- Re-wrote postcode input function to take a custom error message which forces an error style.
=> LGA-1339 LARP page changes

cla_public/apps/checker/cait_intervention.py
- Create a class called `CaitParams` and separate out the functionality of the `get_cait_params` function into methods on the class
The `CaitParams` class has been made into a dict-like object using dict as a base class. The methods on the class set key, value pairs upon itself. It is assigned to the `params` variable and eventually returned when it has been fully configured
=> LGA-455 Simplify cyclomatic complexity of the 'get_cait_params' function

cla_public/static-src/javascripts/modules/availability-times.js
The markup was changed when switching to the design system, breaking the
jQuery selector and therefore causing the time slots not to be updated
and a random one chosen when switching days.
At the moment, the time slots are the same on all days that have time slots (Saturdays
have no slots, rather than reduced hours), so this change won't be as apparent yet.
However, the change that broke this also caused the selector to no longer select a random
time slot when switching dates: this behaviour is also restored by this PR, and can be seen to
be working even with the current operator hours.
=> LGA-1180 - Fix time selector when changing callback day

cla_public/static-src/stylesheets/main.scss
Added suffix to all links with `rel=external` to indicate to screen readers that it is a link to an external website.
=> LGA-1402 External links marked as such for screen readers only

cla_public/templates/checker/about.html, cla_public/templates/macros/form.html
Adds a `pattern` and `inputmode=numeric` to the integer entry fields for _**number of depentants**_ and _**number of children**_.  
Removes the same from the currency fields as per GDS guidelines.  
=> LGA-1407 numbers

cla_public/apps/contact/tests/test_availability.py, requirements/base.txt
cla_common has been updated with [new operator hours](https://github.com/ministryofjustice/cla_common/pull/98)
While this repo does not directly use those changes, it should be kept up to date.
It should not be merged here until it's ready to be used on cla_frontend and cla_backend, just to keep things simple
=> LGA-1382 - Update cla_common for restored operator hours

docker/cla_public.ini
Per https://github.com/getsentry/raven-python/issues/732#issuecomment-176854438
We don't want or need these to reach Sentry
Hard to demonstrate on UAT, as the incidence of this error is effectively zero, there, but as long as we can demonstrate that the site continues to work I think we can merge it and then see on production if it actually solves the problem.
=> LGA-1446 - Ignore noisy, unimportant uwsgi errors

cla_public/apps/contact/forms.py, cla_public/static-src/javascripts/modules/address-finder.js, cla_public/static-src/stylesheets/main.scss, cla_public/templates/contact.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po
Changes question text size for all but address questions.
Adds (optional) suffix to special communication needs question.
Remove postcode repetition from address select.
=> LGA-1404 Comms page text size and optional suffix

docker/cla_public.ini, helm_deploy/cla-public/templates/deployment.yaml
Add preStop lifecycle hook and terminationGracePeriod to allow enough time for uwsgi finish processing requests
Changes explained:
- **die-on-term** - respect the convention of shutting down the instance
- **preStop** - Sleep for 30 seconds. Called before receiving SIGTERM. Aim here is to sleep enough time for the current requests to finish.
- **terminationGracePeriodSeconds** - Amount of time kubernetes waits before sending us the SIGKILL signal.
Important note from the [kubernetes documentation ](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace)on how the preStop and terminationGracePeriodSeconds interact:
> It’s important to note that this(_terminationGracePeriodSeconds_) happens in parallel to the preStop hook and the SIGTERM signal. …
=> LGA-1463 - uwsgi graceful termination workaround 

cla_public/templates/checker/result/_find-legal-adviser.html
Checked for title attribute - if set, that means a title is already used (in laalaa.html).  Otherwise use title as normal.
=> LGA-1475 Two H1s on one page

cla_public/apps/checker/fields.py, cla_public/apps/checker/tests/test_money_field.py, cla_public/javascript-tests/test/currency-input.test.js, cla_public/static-src/javascripts/modules/currencyInputValidation.js, cla_public/static-src/javascripts/modules/form-errors.js, package.json
- Let users optionally add a pound sign to any input requiring an amount to be entered 
- Rewrite validation for the front end which deals with how error classes get added. Validation on front end now matches the validation on the backend
- Write tests for the validation on frontend and backend
- Create a new test/test folder for the frontend validation called `javascript-tests/test`
- Ensure error and non-error colours are consistent for forms that require `an amount and frequency` (like pictured below) or just `an amount`
> Had to work around the fact that the £ sign is a non-ASCII character and python's default encoding is ASCII. Also on the backend, data coming in from the tests comes in byte literal while data coming from the frontend comes in unicode. I attempt to convert both to …
=> LGA-1340 Pound sign prefixing for currency input fields

cla_public/apps/contact/forms.py, cla_public/static-src/javascripts/modules/form-errors.js, cla_public/static-src/javascripts/modules/textarea-character-count.js, cla_public/static-src/stylesheets/main.scss, cla_public/templates/contact.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po
Updated the character counter to use the GDS wording.
- Fewer instead of less
- Preceding the count with "you have"
Fixed the bug where line returns were counted incorrectly.
Fixed the bug where the error JS would remove the character count.
Got rid of a bit of CSS that was causing undesirable things in IE.
=> LGA-1357 character counter

cla_public/static-src/javascripts/modules/form-errors.js
Using JS, every time an error is thrown and hidden fields contain a value, that value is wiped and the submit retried.  
=> LGA-1162 hidden field error

cla_public/templates/macros/form.html, cla_public/templates/macros/subform.html
- Adds in a width class to the other language select field:
- This fixes the still-unexplained bug.
- This also maintains the wide breadth of the select field, increasing click area.
- Added in note for any future development on this, so the bug isn't accidentally re-introduced.
=> LGA-1479 Erratic Other Language Select Class

cla_public/templates/base.html, cla_public/templates/contact.html
Added a class to the postcode input that puts a margin beneath it, so the search button doesn't butt up against it in mobile view.  
Added in a variable for the CSS file - to jolt any return users to refresh their CSS.
=> LGA-1508 Margin for postcode input

cla_public/templates/interstitial.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po
Adds `rel=external` to the sign language link for screen reader assistance etc.  
Adds it to the Welsh translation too.
Moved the Welsh word for "interpreter" into the link to be in line with the English
=> LGA-1515 rel=external for sign language link

cla_public/static-src/stylesheets/_find-legal-adviser.scss
Applies GDS Design System focus styling to the links in the Google Map plugin
=> LGA-1511 LARP link focus styling

cla_public/templates/accessibility-statement.html, cla_public/translations/cy/LC_MESSAGES/messages.po
LGA-1428: Adds new Welsh translations.
LGA-1427: Updates accessibility statement.
LGA-1428 & 1427: Applies Welsh translations to accessibility statement.
=> LGA-1428 & 1427 Welsh Translations and Accessibility Statement update

cla_public/static-src/javascripts/modules/find-legal-adviser.js, cla_public/static-src/stylesheets/_find-legal-adviser.scss
- Adds a JS function to handle skip to main content functionality.
- Neutralized the focus state for results div - ordinarily a non-focusable element.
=> LGA-1541 LARP title duplication bug

requirements/base.txt
Use cla_common version with boxing day hours
=> LGA-1567 - Use cla_common version with boxing day hours

docker/cla_public.ini
Stops filtering out these types of i/o errors from reaching Sentry. These errors may actually have (at least partly) indicated a problem after all. We've added config to cla_backend to try to reduce them, so I'd like to see if that's actually had any effect on them.
=> LGA-1574 - Reinstate noisy, but potentially important uwsgi errors

cla_public/templates/_disregards-info.html, cla_public/templates/checker/income.html, cla_public/templates/checker/savings.html, cla_public/translations/cy/LC_MESSAGES/messages.po
- adds new file for disregard list
- adds the above as part of a details tag in income and savings
- Some Welsh for the different schemes
=> LGA-1547 disregards list

cla_public/apps/checker/constants.py
Comments out old code and makes `traffickingslavery` search for a blank, which returns all providers.  
Old code to be reinstated when new `mosl` category is set up on Production.
=> LGA-1585 Modern Slavery LARP to search all categories

cla_public/static-src/stylesheets/_help-organisations.scss, cla_public/templates/macros/help-orgs.html, cla_public/translations/cy/LC_MESSAGES/messages.po
- Adds translation tag around opening times field allowing translation.
- Adds new CSS class for styling multi-line opening times (as the Welsh translation preserves line-returns).
- Adds Welsh translations for all normal opening times
- Not including a few language-heavy opening times that need translations
=> LGA-1586 alt help opening hours in welsh

cla_public/apps/checker/constants.py, cla_public/apps/scope/views.py
Adding LARP modern slavery label
I also moved all the Category constants next to each other to help with discovering the different types of categories and category codes and their uses.
=> LGA-1637 - LARP modern slavery label

cla_public/apps/contact/views.py, cla_public/config/common.py, cla_public/templates/contact.html, cla_public/templates/macros/emergency_message.html
This adds an emergency message which can be turned off or on with an environment variable called emergency_message_on.  It used the gds notifications style found here:  https://design-system.service.gov.uk/components/notification-banner/
and it displays on the contact page.
=> LGA-1685 Emergency message template

cla_public/translations/cy/LC_MESSAGES/messages.po
This adds the Welsh translations for the ineligible journey where the user is over the disposable capital thresholds.
Welsh translations for ineligible journeys for disposable income will follow when we have translations.
Ticket no 1709
https://dsdmoj.atlassian.net/browse/LGA-1709
=> LGA-1709-welsh-means-capital-ineligible

cla_public/apps/checker/constants.py, cla_public/translations/cy/LC_MESSAGES/messages.po
Updates the ENG text and adds the corresponding Welsh translation.
I've removed redundant words from the original wording in the ticket to shorten the message and cognitive load and so that the message doesn't wrap onto 3 lines on desktop view.
LGA-1649
https://dsdmoj.atlassian.net/browse/LGA-1649
=> LGA-1649-welsh-info-stored-message

requirements/base.txt
Update cla_common to latest version to pull in address lookup changes
*The os-places kubernetes secret needs to be updated with the new api key before deploying this.*
=> LGA-1629 - Update cla_common to latest version to pull in address lookup changes

cla_public/templates/macros/emergency_message.html, cla_public/translations/cy/LC_MESSAGES/messages.po
Add Welsh translation for the emergency message if the CLA helpline is unavailable
https://dsdmoj.atlassian.net/browse/LGA-1737
=> LGA-1737-Welsh-emergency-unavailable-message

cla_public/apps/base/views.py
Refactoring session usage for ReasonsForContacting, which now inherits EnsureSessionExists
=> LGA 1717 - refactor session usage in ReasonsForContacting

cla_public/templates/checker/result/ineligible.html, cla_public/translations/cy/LC_MESSAGES/messages.po
Adds Welsh translations for journeys where the user is ineligible for means for exceeding maximum income and disposable income.
The commits reflect that it was tricky to get the translations to appear and the link wasn't displaying correctly in the English version.
https://dsdmoj.atlassian.net/browse/LGA-1710
=> LGA-1710-welsh-mean-ineligible

cla_public/apps/checker/views.py, cla_public/config/common.py, cla_public/templates/checker/result/eligible.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po, cla_public/translations/messages.pot, helm_deploy/cla-public/values.yaml
- Makes the first paragraph text on the `/results/eliglble` and `/results/provisional` page dynamic based off whether the category is `family` and whether the `family_issue_feature_flag` is True
- Adds a `family_issue_feature_flag` as a Kubernetes config map and django setting variable. When we eventually go live, this will get turnt on (set to True)
- Adds the new family text to the translation files (currently it is there as a placeholder till we get the Welsh translations for them)
=> LGA-1753 CLA Public Family changes

cla_public/static-src/stylesheets/main.scss
- Use new link changes by setting sass variable `$govuk-new-link-styles` to `true`
Has to be imported above `govuk/all` so it does not get overwritten
=> LGA-1812 Change thickness of links in line with latest GDS guidelines

.circleci/config.yml, bin/production_deploy.sh, bin/staging_deploy.sh, bin/staging_multideploy.sh, helm_deploy/cla-public/templates/ingress.yaml, helm_deploy/cla-public/values.yaml
- Add variable placeholders for cluster `name` and `weight` in `values.yaml`
- Add annotations to `ingress.yml` referencing the variables above
- Add parameters to all deployment scripts for setting (overriding) the cluster `name` and `weight` in `values.yaml`
- Create a `ingress-cluster` configmap with following values
- `name` The cluster name i.e `blue` or `green`
- `weight` The weighting of traffic that cluster should receive
- Update the circle config to read contents of `ingress-cluster` configmap and pass it to the deploy scripts as environment variables.
Similar to https://github.com/ministryofjustice/cla_backend/pull/736
Command used to create configmap: `kubectl create configmap ingress-cluster --from-literal=name=blue --from-literal=weight=100`
=> LGA-1895 - Add external DNS annotations to ingress

.circleci/config.yml
Deploy staging to live
Rename live-1 staging deployments with a suffix of `live1`
=> LGA-1925 deploy staging to live

.circleci/config.yml, helm_deploy/cla-public/templates/ingress.yaml
updated ingress api version and also upgraded helm version to avoid helm bug when trying to reuse a existing resource
Need to manually annotate existing ingress resources in all namespaces before running workflows:
NAME=***
RELEASE=***
NAMESPACE=***
kubectl annotate $KIND $NAME meta.helm.sh/release-name=$RELEASE
kubectl annotate $KIND $NAME meta.helm.sh/release-namespace=$NAMESPACE
=> LGA-1938-remove-deprecated-extensions-ingress-api

helm_deploy/cla-public/templates/ingress.yaml
updated ingress so that modsec ignores json to see if this is causing increase in sentry issues.
=> LGA-2125 updated ingress so that modsec ignores json

cla_public/templates/_disregards-info.html
Updates the income disregard content to show that the energy pries act 2022 and cost of living payment from the social security act 2022 do not count towards income. 
As a result of updating the disregards template, the what payments do not count as savings section has also been updated.
=> LGA-2401 update income disregard template

helm_deploy/cla-public/templates/dashboard.yml
Adds quotes around `cla-public.fullname` in dashboard.yml for title value.
Cloud platform has reported erroring which is preventing us from adding new dashboards, we have a hack but it involves us restarting pods every time somebody wants to add a new dashboard. Here's the error:
logger=provisioning.dashboard type=file name=sidecarProvider t=2023-04-05T11:53:29.832085199Z level=error msg="failed to load dashboard from " file=/tmp/dashboards/laa-cla-public-staging-dashboard.json error="invalid character 'l' looking for beginning of value"
[cla_public/dashboard.yml at 432bdfb7244ccc22035846a5350890ac068c21a1 · ministryofjustice/cla_public](https://github.com/ministryofjustice/cla_public/blob/432bdfb7244ccc22035846a5350890ac068c21a1/helm_deploy/cla-public/templates/dashboard.yml) …
=> LGA-2420 adding quotes around title value

.circleci/config.yml
Now both match more up to date image used for staging - this means that the slack notification works because the certificate is up to date.
Required.
=> LGA-2423 ITHC update images ADDITION

cla_public/apps/contact/tests/test_mail.py, cla_public/apps/contact/views.py, cla_public/config/common.py
We previously used Sendgrid to send emails and have moved to using Notify. These emails are only sent in English.
Using Sendgrid, the email text were translated and then sent over. This is not possible in Notify, the template needs to be in Welsh.
Mirrors the original code as it does not send welsh email if you have ticked welsh on the form but haven’t chosen to view pages in welsh.
I haven't added any tests as I figured there are already tests for checking the locale. Can add if you think it is worth it.
I believe I have added in the Welsh translations. Someone will need to check those though...
Mirrors the original code as it does not send welsh email if you have ticked welsh on the form but haven’t chosen to view pages in welsh.
Need to make a decision on whether to keep the old …
=> LGA-2454 Add Welsh Translations for Notify Emails

cla_public/apps/contact/views.py, cla_public/config/common.py
Adds a third party confirmation email with welsh translations.
- https://dsdmoj.atlassian.net/jira/software/c/projects/LGA/boards/226?modal=detail&selectedIssue=LGA-2457
- Add template to Gov Notify
- Verify welsh template
=> LGA-2457 Added third party confirmation email with welsh translation

cla_public/apps/base/tests/test_extensions.py, cla_public/apps/base/views.py
Return 503 status code when in maintenance mode
Like the rest of our apps, update public to return a 503 status code when in maintenance mode. It is currently returning a 200 status code even though it is maintenance mode.
=> Return 503 status code when in maintenance mode

cla_public/apps/contact/tests/test_mail.py, requirements/generated/requirements-dev.txt, requirements/generated/requirements-production.txt, requirements/generated/requirements-testing.txt, requirements/source/requirements-base.in
Disable callbacks for today due to phone system not working
Had to upgrade from pytz==2018.5 to pytz==2021.1 because cla_common uses pytz==2021.1 otherwise we couldn't include cla_common due to that conflict
Updated tests that were doing callbacks for today if the tests ran before 14:30 to instead use tomorrows date for callbacks. There is no logic for only making today callbacks available before 14:30
=> Disable callbacks for today due to phone system not working

requirements/generated/requirements-dev.txt, requirements/generated/requirements-production.txt, requirements/generated/requirements-testing.txt, requirements/source/requirements-base.in
Update tag for cla_common so can disable callbacks for Friday 28th July 2023
=> Disable operator hours for 28th July 23

package.json
Bumps GOV Frontend Components to allow exit page CSS to be used within our live site. 
- [https://design-system.service.gov.uk/components/exit-this-page/](GDS Exit page component.)
- [https://lga-2612-bump-govuk-frontend.staging.checklegalaid.service.gov.uk/start](Staging environment for manual testing.)
- [https://dsdmoj.atlassian.net/browse/LGA-2622](LGA-2622)
=> LGA-2612 bumping gov frontend

Dockerfile
Adds arguments to the dockerfile to allow it to be built different on M1 E2E tests
=> M1 e2e public fixes

.gitignore, docs/installation.md
Fixes the python2 suggested install.
I couldn't get brew to install it - I guess it's taken out as it's out of date.
Devs on CLA team say they use pyenv: https://mojdt.slack.com/archives/CFUESB43G/p1661956186094889?thread_ts=1661956005.152889&cid=CFUESB43G
`pyenv local 2.7.18` causes `.python-version` to be written. I think the intention behind it being a dot-file is that it should be gitignored rather than checked in, to give developers a bit of control.
=> Install python2 with pyenv because brew no longer has it

cla_public/translations/en/LC_MESSAGES/messages.po
Fixes one error message "There was a problem" appearing in Welsh
=> LGA-2798: Fixed error message appearing in Welsh

helm_deploy/cla-public/templates/ingress.yaml
This request removes security rule 942230 from modsec which has been causing a false positive.
https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.3/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L221
This rule was preventing any input field from putting 'having £' as it was viewing this as an SQL injection. Although this is an edge case this has occurred and blocked this on our system.
Disable Rule 930120; this rule is showing an OS File Access Attempt but is being caused by .nsr included in cookies which is added at random.
Disable Rule 933210; this rule shows as PHP Injection Attack when someone enters )( into a field; this is blocking legitimate requests so needs to be disabled ASAP, also we don't use PHP anyway
=> Remove rule SecRuleRemoveById 942230

cla_public/templates/checker/result/_find-legal-adviser.html
- Fixes an issue where the input field was wrongly removed when an invalid postcode was entered.
- Moves the warning banners to the top of the list.
=> LGA-3047: Fixed bug where postcode input disappeared when invalid postcode entered

cla_public/templates/checker/result/find-legal-adviser-search/form.html, cla_public/templates/checker/result/find-legal-adviser-search/index.html, cla_public/templates/checker/result/find-legal-adviser-search/result.html, cla_public/templates/macros/find-legal-adviser.html
Now only attempts to render the category caption when `category_name` is present.
=> LGA 3027 Display postcode errors

cla_public/apps/checker/views.py, cla_public/templates/checker/result/eligible-f2f.html, cla_public/templates/checker/result/face-to-face.html, cla_public/templates/checker/result/find-legal-adviser-search/form.html, cla_public/templates/laalaa.html, cla_public/templates/macros/find-legal-adviser.html
Fixes an issue where references to the now removed `_find_a_legal_advisor.html` template were still present.
When the user is eligible for legal aid with the benefits category they are presented with mini fala as expected.
This page matches the page before the HLPAS changes were introduced.
Removes all references to the now removed `_find_a_legal_advisor.html`
=> LGA-3077 Fix misdirect issue for benefits category

.circleci/define_build_environment_variables, bin/pingdom_ips.py, bin/production_deploy.sh, bin/staging_deploy.sh, bin/staging_multideploy.sh, helm_deploy/cla-public/templates/_helpers.tpl, helm_deploy/cla-public/templates/ingress.yaml, helm_deploy/cla-public/values-production.yaml, helm_deploy/cla-public/values.yaml
Disable indexing and whitelisting of Non-Production environments
Pingdom IP addresses also needed to be added to the whitelist. However these frequently change, so an additional script is added to discover these IP addresses.
=> LGA-2991 - Disable indexing and whitelisting of Non-Production environments

cla_public/static-src/javascripts/modules/gtm-data.js
Part of a series of event tracking tickets. Sends information about about simple click events and updates to Google Tag Manager for forwarding to Google Analytics.
Complex events e.g. Find address button is not interfered with to keep code clean, unless we really need it. But this covers most of the clicks and updates.
The new JS file is likely to have more events as time goes on.
=> LGA-3175 Track click and change events

Dockerfile, cla_public/apps/checker/tests/test_payloads.py, cla_public/apps/contact/forms.py, cla_public/apps/contact/tests/test_validation.py, cla_public/apps/contact/views.py, cla_public/static-src/javascripts/modules/bsl_email.js, cla_public/static-src/javascripts/modules/form-errors.js, cla_public/static-src/stylesheets/_forms.scss, cla_public/templates/macros/form.html, cla_public/templates/macros/subform.html, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po, cla_public/translations/messages.pot, docker-compose.yml
- Add BSL E-mail field
- Remove `Minicom – for textphone users` adaptation option
- Reword adaptation options
=> LGA-3158 - Add BSL E-mail field

cla_public/static-src/javascripts/modules/gtm-data.js, cla_public/templates/contact.html
Sends page load time and label to GA
Introduced variable_label and variable_number as re-usable custom dimensions in GA4 for non-business-specific generic use - so we don't run out (limit 50)
=> LGA-2847 Track page load time on GA

cla_public/apps/contact/forms.py, cla_public/translations/cy/LC_MESSAGES/messages.po, cla_public/translations/en/LC_MESSAGES/messages.po, cla_public/translations/messages.pot
- Updates both instances of the text "Phone number for the callback" to "Phone number" to reflect the latest content record.
- Updates the Welsh translation for these to reflect the latest content record.
=> LGA-2931: Correct contact content

cla_public/static-src/javascripts/modules/properties.js
Fix broken add property button
The promise returned from $.post no longer has a `success `method. Instead the `done` method should be used
From the jquery docs:
> Deprecation Notice
The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callback methods are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.
The bug was probably introduced around the same time that the jquery version was upgraded in #1220
=> LGA-3339 - Fix broken add property button
